// Brothers profile data
const brothersData = {
    'Aidan Chan': {
        image: 'brothers/Aidan Chan.jpg',
        fullName: 'Aidan Chan',
        pledgeClass: 'Rho',
        graduationDate: 'May 2027',
        major: 'Business Major / Specialization in Finance',
        bio: 'Hey, I\'m Aidan. Started cutting hair for friends in my dorm room and it turned into Herb Fades—now I\'m serving 150+ clients on campus. I like seeing how a good cut can change someone\'s confidence. When I\'m not cutting hair or studying, I\'m usually playing basketball or grabbing food with friends.',
        dspPositions: '',
        committees: 'Philanthropy (Fall 2025)',
        careerInterests: 'Financial Analyst, Starting and owning my own barbershop',
        pastRoles: 'Founder at Herb Fades (Dec 2022 - Present), Food Server at Luigi\'s Restaurant & Bar (Jul 2022 - Aug 2023), Customer Service Representative at eFresh (Jul 2020 - Oct 2021)',
        linkedin: 'https://www.linkedin.com/in/aidanchan27',
        email: 'aidan.chan@stonybrook.edu',
        hobbies: 'Basketball, eating, playing games',
        funFact: 'I am recently bilingual',
        personality: 'Smile, outgoing, chill',
        favoriteMemory: 'Baking and playing games with my fellow brothers',
        littleQualities: ''
    },
    'Ana Jiang': {
        image: 'brothers/Ana Jiang.jpeg',
        fullName: 'Ana Jiang',
        pledgeClass: 'Rho',
        graduationDate: 'May 2027',
        major: 'Business Management with Specialization in Operations, Minor in Accounting',
        bio: 'Hi, I\'m Ana. I like bringing people together and helping them find opportunities that fit. Whether it\'s organizing events or working in HR, I enjoy the problem-solving side of operations. When I\'m not working, I\'m usually hiking, traveling, or trying to find the best matcha in town.',
        dspPositions: 'Philanthropy Chair (Fall 2025)',
        committees: 'Standards, Philanthropy (Fall 2025)',
        careerInterests: 'Human Resources, Audit',
        pastRoles: 'Student Engagement Specialist at Ion Philanthropy (Oct 2025 - Present), Undergraduate Teaching Assistant at Stony Brook University (Aug 2025 - Present), Philanthropy Chairperson at Delta Sigma Pi (May 2025 - Present), Human Resources Manager at Fourier Fund (Mar 2025 - Present), Operations & Talent Management Intern at SBU Career Center (Aug 2024 - May 2025), Sales Associate at Rumi Life (Oct 2023 - May 2025)',
        linkedin: 'https://www.linkedin.com/in/ana-jiang',
        email: 'ana.jiang@stonybrook.edu',
        hobbies: 'Hiking, traveling, taking pictures, and LOVE MATCHA',
        funFact: '',
        personality: '',
        favoriteMemory: '',
        littleQualities: ''
    },
    'Camila Sanchez': {
        image: 'brothers/Camila Sanchez.JPG',
        fullName: 'Camila Sanchez',
        pledgeClass: 'Rho',
        graduationDate: 'May 2028',
        major: 'Business Major specializing in Marketing',
        bio: 'Hey, I\'m Camila. I handle social media and recruitment for DSP, and I enjoy the creative side of marketing—designing posts and telling brand stories. When I\'m not working on content, I\'m listening to music (big Lana del Rey fan), reading, or working on coloring books. Fair warning: I\'m terrified of bugs.',
        dspPositions: 'Social Media Chair (Fall 2025), Recruitment Chair (Spring 2026)',
        committees: 'CS/ Philanthropy (Fall 2025), AR/ Philanthropy (Spring 2026)',
        careerInterests: 'Marketing, Public Relations',
        pastRoles: 'Social Media Chair at Delta Sigma Pi (May 2025 - Present), Residential Ambassador at Stony Brook University (Jun 2025 - Jul 2025), Project and Event Coordinator Intern at SBU, Childcare Worker at Marks JCH of Bensonhurst (Sep 2022 - Jun 2024)',
        linkedin: 'https://www.linkedin.com/in/camila6',
        email: 'camila.sanchezsantamaria@stonybrook.edu',
        hobbies: 'Music, Coloring books, Reading, Dance',
        funFact: 'I love dying my hair, I\'m a huge fan of Lana del Ray and The Neighbourhood, and I am scared of bugs',
        personality: 'Bright, SMILE, Hardworking',
        favoriteMemory: 'Going out to any social event with my friends in DSP',
        littleQualities: ''
    },
    'Chanul Dandeniya': {
        image: 'brothers/Chanul Dandeniya.jpeg',
        fullName: 'Chanul Dandeniya',
        pledgeClass: 'Rho',
        graduationDate: 'May 2027',
        major: 'Computer Science, Applied Mathematics & Statistics',
        bio: 'What\'s up, I\'m Chanul. I work on software engineering and product management, mostly focused on building things that actually solve problems. Spent time at Amazon and some startups, which taught me a lot about scaling systems and thinking through technical challenges. When I\'m not coding, I\'m at the gym, working on side projects, or hanging out with friends.',
        dspPositions: '',
        committees: '',
        careerInterests: 'Software Engineering, Technical Product Management, Startup Culture',
        pastRoles: 'Junior Developer at Amazon (Oct 2021 - Oct 2024), Machine Learning Intern at SAI AI, Lead Solutions Architect at OuterLabs Studio (Aug 2022 - Jun 2025)',
        linkedin: 'https://www.linkedin.com/in/cdandeniya/',
        email: 'chanul.dandeniya@stonybrook.edu',
        hobbies: 'Gymming, building apps, basketball, real estate, investing, spontaneity',
        funFact: '',
        personality: '',
        favoriteMemory: 'Skydiving with my big and chilling with the brothers',
        littleQualities: ''
    },
    'Sandra Obrycki': {
        image: 'brothers/Sandra Obrycki.png',
        fullName: 'Sandra Obrycki',
        pledgeClass: 'Nu',
        graduationDate: 'May 2026',
        major: 'Business Management Specializing in Marketing & Finance',
        bio: 'Hi, I\'m Sandra! I\'m passionate about fashion and brand marketing, combining my love for business strategy with creative storytelling. Currently serving as VPPA, I\'ve been involved in various leadership roles within DSP. When I\'m not working on marketing campaigns or planning events, I enjoy baking, pilates, reading, shopping, and hiking. I studied abroad in Italy for a summer, which was an incredible experience.',
        dspPositions: 'Social Chair (Spring 2024), PE (Spring 2025), VPPA (25-26)',
        committees: 'Professional Development, Philanthropy (Fall 2024 - Fall 2025)',
        careerInterests: 'Fashion/Brand Marketing',
        pastRoles: 'Marketing Intern at Eagle Rock Properties (Summer 2025 - Present), Marketing Intern at SBU Budget, Financial Planning & Analysis (Past)',
        linkedin: 'http://linkedin.com/in/sandra-obrycki',
        email: 'sandra.obrycki@stonybrook.edu',
        hobbies: 'Baking, Pilates, Reading, Shopping, Hiking',
        funFact: 'Studied abroad in Italy for a summer',
        personality: 'Bubbly, compassionate, kind',
        favoriteMemory: 'Going to dinners with my littles!!',
        littleQualities: ''
    },
    'Vincent Ouyang': {
        image: 'brothers/Vincent Ouyang.jpg',
        fullName: 'Vincent Ouyang',
        pledgeClass: 'Nu',
        graduationDate: 'May 2026',
        major: 'Business Management / Finance / Marketing',
        bio: 'Hey, I\'m Vincent. I\'m a strategy analyst passionate about using data and business insights to drive decisions. I\'ve served as Social Chair and PEA in DSP, and I\'m also the President and Captain of the Volleyball Club at Stony Brook. When I\'m not analyzing business strategies or playing volleyball, you can find me bowling, at the gym, or just hanging out with friends.',
        dspPositions: 'Social Chair (Fall 2023), PEA (Spring 2025)',
        committees: 'Philanthropy (Fall 2024), PDC (Fall 2025)',
        careerInterests: 'Strategy Analyst',
        pastRoles: 'Business Intern at Lishawn\'s Consulting (Summer 2024, Summer 2023), Social Event Coordinator at Delta Sigma Pi (Apr 2023 - Apr 2024), Intern at Upkey (Jul 2021 - Sep 2021), President and Captain of Volleyball Club at Stony Brook',
        linkedin: 'https://www.linkedin.com/in/vincent-ouyang-o9/',
        email: 'vincent.ouyang@stonybrook.edu',
        hobbies: 'Volleyball, Bowling, Going to the Gym',
        funFact: 'Eat, sleep, rave',
        personality: 'Crazy, Chill, Paranoid',
        favoriteMemory: 'Formal/Hoco: Hanging with all the goofs',
        littleQualities: ''
    },
    'Michelle Weng': {
        image: 'brothers/Michelle Weng.jpeg',
        fullName: 'Michelle Weng',
        pledgeClass: 'Nu',
        graduationDate: 'May 2026',
        major: 'Business Management, Finance Specialization, Accounting Minor',
        bio: 'Hi, I\'m Michelle! I\'m focused on accounting and finance, with experience at NYC Health + Hospitals, KPMG, and Point72. I\'ve served as Recruitment Chair, PEA, and VPPA in DSP, and I also work as a Peer Career Coach and Data Analyst Intern at the SBU Career Center. When I\'m not crunching numbers or helping students with their careers, I enjoy matcha, karaoke, baking, and traveling.',
        dspPositions: 'Recruitment Chair (Fall 2023), PEA (Spring 2024), VPPA (24-25)',
        committees: 'Philanthropy (Spring 2025)',
        careerInterests: 'Accounting and Finance',
        pastRoles: 'Incoming Tax Intern at KPMG US (Aug 2025 - Present), Regulatory Reporting Intern at Point72 (Jun 2025 - Aug 2025), Data Analyst Intern at Stony Brook University Career Center (Aug 2024 - May 2025), Senior Peer Career Coach Intern at Stony Brook University Career Center (May 2024 - May 2025), Peer Career Coach Intern at Stony Brook University Career Center (Aug 2023 - May 2024), Embark Scholar Intern at KPMG US (Jun 2024 - Aug 2024), Winter Finance Intern at NYC Health + Hospitals (Dec 2023 - Jan 2024)',
        linkedin: 'https://www.linkedin.com/in/-michelle-weng',
        email: 'Michelle.weng.1@stonybrook.Edu',
        hobbies: 'Matcha, karaoke, baking, travel',
        funFact: '',
        personality: '',
        favoriteMemory: '',
        littleQualities: ''
    },
    'Daniel Yoo': {
        image: 'brothers/Daniel Yoo.jpg',
        fullName: 'Daniel Yoo',
        pledgeClass: 'Nu',
        graduationDate: 'May 2026',
        major: 'Applied Mathematics & Statistics, Economics',
        bio: 'Hey, I\'m Daniel. I\'m passionate about using quantitative analysis and strategic thinking to support financial decision-making. I\'ve served as VP Scholarships & Awards, Social Chair, and PE in DSP. Currently interning at Wells Fargo in Consumer Lending, I\'ve also worked at World Insurance Associates and the SBU Career Center. When I\'m not analyzing data or working on financial models, I enjoy playing volleyball.',
        dspPositions: 'VP Scholarships & Awards (23-24), Social Chair (Spring 2025), PE (Fall 2025)',
        committees: 'Professional Development, Philanthropy',
        careerInterests: 'I\'m passionate about using quantitative analysis and strategic thinking to support financial decision-making.',
        pastRoles: 'Consumer Lending Intern at Wells Fargo (Jun 2025 - Present), Risk Management Intern at World Insurance Associates LLC (May 2024 - May 2025), Operations and Talent Management Intern at Stony Brook University Career Center (Aug 2023 - May 2024), Financial Planning Analyst Intern at Delta Galil Industries (Apr 2023 - Aug 2023)',
        linkedin: 'https://www.linkedin.com/in/daniel-yoo-/',
        email: 'daniel.yoo@stomybrook.edu',
        hobbies: 'Volleyball',
        funFact: '',
        personality: '',
        favoriteMemory: '',
        littleQualities: ''
    },
    'Rainer Duchmanh': {
        image: 'brothers/Rainer Duchmanh.jpeg',
        fullName: 'Rainer Duchmanh',
        pledgeClass: 'Xi',
        graduationDate: 'May 2026',
        major: 'Business Administration and Management, Finance / Economics',
        bio: 'Hi, I\'m Rainer. I\'m focused on wealth management and financial analysis, currently interning at Snyder Wealth Group and serving as Junior Analyst at Fourier Fund. I\'ve also worked as a sports coach and summer camp counselor, which has helped me develop strong leadership and communication skills. When I\'m not working on financial planning or analyzing markets, I enjoy playing soccer.',
        dspPositions: 'Alumni Relations Chair (Fall 2024)',
        committees: 'Alumni Committee',
        careerInterests: '',
        pastRoles: 'Wealth Management Intern at Snyder Wealth Group (May 2024 - Present), Junior Analyst at Fourier Fund of Stony Brook University (Feb 2025 - Aug 2025), Sports Coach at F.A.S.T. Athletics (Sep 2023 - May 2024), Head Summer Camp Counselor at Elmsford Day Camp (Jun 2023 - Aug 2023), Summer Camp Counselor at Future Stars Summer Camps (Jun 2022 - Aug 2022)',
        linkedin: 'https://www.linkedin.com/in/rainer-ducmanh/',
        email: 'rainer.ducmanh@stonybrook.edu',
        hobbies: 'Soccer',
        funFact: '',
        personality: '',
        favoriteMemory: '',
        littleQualities: ''
    },
    'Karan Grover': {
        image: 'brothers/Karan Grover.JPG',
        fullName: 'Karan Grover',
        pledgeClass: 'Xi',
        graduationDate: 'May 2026',
        major: 'Applied Mathematics & Statistics and Economics',
        bio: 'Hey, I\'m Karan. I\'m passionate about data analytics, consulting, and HR analytics. Currently serving as President of Delta Sigma Pi, I\'ve held various leadership roles including VPAR and Alumni Relations Chair. I\'ve interned at PSEG in People Analytics and worked as a Peer Career Coach at the SBU Career Center. When I\'m not analyzing workforce data or leading chapter initiatives, I enjoy watching sports (F1 and Basketball), listening to music, and watching movies.',
        dspPositions: 'Alumni Relations Chair (Spring 2024), VPAR (24-25), President (25-26)',
        committees: 'Alumni Relations (Spring 2024)',
        careerInterests: 'Data Analytics, Consulting, and HR Analytics',
        pastRoles: 'President at Delta Sigma Pi Upsilon Omega (Apr 2025 - Present), Vice President of Alumni Relations at Delta Sigma Pi (Apr 2024 - Apr 2025), Alumni Chair at Delta Sigma Pi (Jan 2024 - Apr 2024), People Analytics Intern at PSEG (Jun 2025 - Dec 2025), Peer Career Coach at Stony Brook University Career Center (Aug 2024 - May 2025), Data Entry Intern at International Rescue Committee (Jun 2024 - Aug 2024), Summer Housing Assistant at Stony Brook University (May 2024 - Aug 2024), Student Services Intern at Stony Brook University (Jan 2024 - May 2024)',
        linkedin: 'https://www.linkedin.com/in/karan-grover-2005kg/',
        email: 'karan.grover@stonybrook.edu',
        hobbies: 'Watching Sports (F1 and Basketball), Listening to music, Watching movies',
        funFact: 'I skipped a grade',
        personality: 'Inquisitive',
        favoriteMemory: 'Picking up all my littos',
        littleQualities: ''
    },
    'Adrian Morel': {
        image: 'brothers/Adrian Morel.jpg',
        fullName: 'Adrian Morel',
        pledgeClass: 'Xi',
        graduationDate: 'May 2026',
        major: 'Business Management and a minor in Applied Mathematics and Statistics',
        bio: 'Hi, I\'m Adrian. I\'m passionate about asset management and financial analysis, with experience interning at JPMorgan Chase. I\'ve served as Senior Vice President and Recruitment Chair in DSP, and I also work part-time at Target and Starbucks. When I\'m not analyzing portfolio exposures or managing recruitment events, I enjoy balancing my work responsibilities and contributing to our chapter\'s success.',
        dspPositions: 'Recruitment Chair (Fall 2023), SVP (24-25)',
        committees: 'Philanthropy (Spring 2026)',
        careerInterests: '',
        pastRoles: 'Customer Service Advocate/Fulfillment Expert at Target (Oct 2021 - Present), Barista at Starbucks (Aug 2022 - Present), Asset Management Summer Analyst at JPMorgan Chase (Jun 2024 - Aug 2025), Senior Vice President at Delta Sigma Pi (Apr 2024 - Apr 2025), Recruitment Chair at Delta Sigma Pi (Dec 2023 - May 2024), Sales Floor Team Member at Michaels Stores (Aug 2020 - Oct 2021)',
        linkedin: 'https://www.linkedin.com/in/adrian-morel1/',
        email: 'adrian.morel@stonybrook.edu',
        hobbies: '',
        funFact: '',
        personality: '',
        favoriteMemory: '',
        littleQualities: ''
    },
    'Laaibah Shoaib': {
        image: 'brothers/Laaibah Shoaib.JPG',
        fullName: 'Laaibah Shoaib',
        pledgeClass: 'Xi',
        graduationDate: 'May 2026',
        major: 'Technological Systems Management, specialization in Information Systems, minor in Film and Screen Studies',
        bio: 'Hi, I\'m Laaibah! I\'m passionate about technical project management, business analytics, and the media and entertainment industry. Currently serving as Recruitment Chair in DSP, I\'ve worked as a Budget Intern at SBU, Writing Tutor, Peer Mentor for CEAS, and held various project management and business development internships. I\'m also a participant in the Emma Bowen Foundation Launch Career Activation Program. When I\'m not managing projects or analyzing data, I enjoy reading, listening to music and making playlists, fashion, shopping, and watching movies.',
        dspPositions: 'Recruitment Chair',
        committees: 'CS, Academic Success',
        careerInterests: 'Technical Project Management, Business Analytics, interest in media and entertainment industry',
        pastRoles: 'Launch Career Activation Program Participant at Emma Bowen Foundation (Jan 2026 - Present), Budget, Financial Planning, and Analysis Intern at Stony Brook University (Jun 2025 - Present), Writing Tutor at Stony Brook University (Feb 2024 - Aug 2025), Media Research Intern at TVB (Aug 2025 - Dec 2025), Business Development Intern at Remotely Good (Jul 2025 - Aug 2025), Project Management Team Lead at JBIER Inc. (May 2025 - Jul 2025), Project Management Intern and Assistant to the Founder at JBIER Inc. (Feb 2025 - Jul 2025), Peer Mentor for CEAS, South Asian Student Alliance Cabinet Member',
        linkedin: 'https://www.linkedin.com/in/laaibah-shoaib',
        email: 'laaibah.shoaib@stonybrook.edu',
        hobbies: 'Reading, listening to music + making playlists, fashion, shopping, watching movies',
        funFact: 'I played violin for 8 years',
        personality: '',
        favoriteMemory: '',
        littleQualities: ''
    },
    'Brian Ren': {
        image: 'brothers/Brian Ren.jpg',
        fullName: 'Brian Ren',
        pledgeClass: 'Omicron',
        graduationDate: 'May 2026',
        major: 'Business Management and a minor in Accounting and Applied Math and Statistics',
        bio: 'Hi, I\'m Brian. I\'m focused on accounting and audit, with experience at KPMG as an Embark Scholar Intern and incoming Audit Intern. I\'ve also worked as a Tax Intern and volunteered with VITA for tax preparation. I\'ve served as Philanthropy Chair in DSP and enjoy teaching and working with students.',
        dspPositions: 'Philanthropy Chair (Fall 2024)',
        committees: 'Philanthropy (Fall 2024), Standards (Fall 2025)',
        careerInterests: '',
        pastRoles: 'Incoming Audit Intern at KPMG US (Aug 2025 - Present), Embark Scholar Intern at KPMG US (Jun 2025 - Aug 2025), Tax Intern at Strategic Financial & Tax Planning Services (Jan 2024 - Apr 2024), Volunteer at Bethpage VITA (Jan 2024 - Apr 2024), Lead Teacher at NORY, Inc. (Jun 2023 - Aug 2023), Counselor at SYEP (Jun 2022 - Aug 2022)',
        linkedin: 'https://www.linkedin.com/in/brian-ren/',
        email: 'brian.ren@stonybrook.edu',
        hobbies: '',
        funFact: '',
        personality: '',
        favoriteMemory: '',
        littleQualities: ''
    },
    'Estella Saha': {
        image: 'brothers/Estella Saha.jpeg',
        fullName: 'Estella Saha',
        pledgeClass: 'Omicron',
        graduationDate: 'May 2026',
        major: 'Applied Mathematics & Statistics, Philosophy minor',
        bio: 'Hey, I\'m Estella! I\'m passionate about quant finance, data science, and research. Currently serving as VP of Film Club and doing quant research on campus, I\'ve been involved in various research projects, tutoring, and clubs. I\'ve served as Marketing Chair in DSP and enjoy art, anime, film, video games, music, photography, fashion, chess, philosophy, and reading.',
        dspPositions: 'Marketing Chair (Fall 2024)',
        committees: 'Philanthropy (Spring 2025)',
        careerInterests: 'Quant, finance, data science',
        pastRoles: 'Vice President at Stony Brook University Reel Rendevous (Film Club) (Jan 2024 - Present), Undergraduate Quant Finance Researcher at Stony Brook University (Aug 2023 - Present), Research Assistant at Vertically Integrated Projects - Automotive Ethics Team (Sep 2024 - May 2025), Linear Algebra Tutor at Academic Success and Tutoring Center at Stony Brook University (Aug 2023 - May 2025), Research Assistant at Mckinnon Rosati Lab (Sep 2024 - Jan 2025), VIP team member, Investment Club Secretary, Bioinformatics research, Blockchain lab member, Chess club member, ASTC tutor, SAT math instructor, Elementary math and reading instructor, DPLN participant, Project Destined intern, Hall council senator',
        linkedin: 'https://www.linkedin.com/in/estellasaha',
        email: 'estella.saha@stonybrook.edu',
        hobbies: 'Art, anime/manga/manhwa, film, video games (silent hill, resident evil, life is strange, dangan, gacha, rhythm, etc), music (crystal castles, Radiohead, Russian music, fakemink hyper pop, etc), photography, fashion, chess, leftist politics, philosophy, books (Dostoevsky, Dazai, Satre, Camus etc)',
        funFact: 'I\'ve been told I look like Jenna Ortega well over 50 times',
        personality: 'Lowkey a narcissist',
        favoriteMemory: 'Making tiramisu',
        littleQualities: ''
    },
    'Naoki Sekine': {
        image: 'brothers/Naoki Sekine.jpeg',
        fullName: 'Naoki Sekine',
        pledgeClass: 'Omicron',
        graduationDate: 'May 2026',
        major: 'Business Management, specializing in Marketing & Double Major in Economics',
        bio: 'Hi, I\'m Naoki! I\'m passionate about marketing analysis and advertising. Currently serving as VPAR in DSP and working as Senior Marketing Intern at the SBU Career Center, I\'m also Vice President of the Japanese Student Organization and a content creator with 990k+ followers on TikTok. I\'ve served as Webmaster and VPAR in DSP, and I enjoy speed stacking, walks, hanging out with friends, and Japanese culture/music.',
        dspPositions: 'Webmaster (Fall 2024), VPAR (25-26)',
        committees: 'Philanthropy (Spring 2025), PDC, AR',
        careerInterests: 'Marketing Analysis, Advertising',
        pastRoles: 'Senior Marketing Intern at Stony Brook University Career Center (May 2025 - Present), Marketing Intern at Stony Brook University Career Center (Aug 2024 - May 2025), Vice President of Alumni Relations at Delta Sigma Pi Upsilon Omega (Apr 2025 - Present), Alumni Committee at Delta Sigma Pi (Dec 2024 - Apr 2025), Professional Development Committee at Delta Sigma Pi (Dec 2024 - Apr 2025), Webmaster Chair at Delta Sigma Pi (May 2024 - Dec 2024), Vice President at Japanese Student Organization (May 2024 - May 2025), Fundraiser Committee at Japanese Student Organization (May 2025 - Present), Historian at Japanese Student Organization (May 2023 - May 2024), Freshmen Representative at Japanese Student Organization (Aug 2022 - May 2023), Digital Strategy & Activation Intern at Publicis Groupe, Content Creator on TikTok (@naoki_sekine) (Mar 2019 - Present), Content Creator on Instagram (@naoki_sekine) (Sep 2022 - Present)',
        linkedin: 'https://www.linkedin.com/in/naoki-sekine',
        email: 'Naoki.sekine@stonybrook.edu',
        hobbies: 'Speed Stacking, walks, hanging out with friends, Japanese culture/music',
        funFact: 'I\'m 12% Korean',
        personality: 'Fast-paced, energetic, reliable',
        favoriteMemory: 'Attending LEAD conference for the first time',
        littleQualities: ''
    },
    'Carrie Song': {
        image: 'brothers/Carrie Song.JPG',
        fullName: 'Carrie Song',
        pledgeClass: 'Omicron',
        graduationDate: 'Fall 2026',
        major: 'Business (Marketing and Operations) Minor in Communication',
        bio: 'Hi, I\'m Carrie! I\'m passionate about HR and currently serving as SVP in DSP. I\'ve served as Social Media Chair and DEI Chair, and I\'ve interned at NYC Health and Hospitals Bellevue and Rudin in HR. I also work as an Office Assistant at SBU Campus Residences. When I\'m not working on HR initiatives or managing social media, I enjoy reading, shopping, traveling, trying new foods, and going to concerts.',
        dspPositions: 'Social Media Chair (Fall 2024), DEI Chair (Spring 2025), SVP (25-26)',
        committees: 'Professional Development (Spring 2025)',
        careerInterests: 'HR',
        pastRoles: 'Senior Vice President at Delta Sigma Pi Upsilon Omega (May 2025 - Present), Diversity, Equity and Inclusion Chair at Delta Sigma Pi (Dec 2024 - May 2025), Social Media Chair at Delta Sigma Pi (May 2024 - Jan 2025), Campus Residences Office Assistant at Stony Brook University (Jan 2025 - Present), Orientation Leader at Stony Brook University (Jan 2024 - Jul 2025), Diversity, Equity and Inclusion Chair at Women In Business at Stony Brook University (Aug 2024 - May 2025), Member at Women In Business at Stony Brook University (Aug 2023 - Present), Human Resources Intern at Rudin (Jun 2025 - Aug 2025), Human Resources Intern at NYC Health+Hospitals | Bellevue (May 2024 - Aug 2024)',
        linkedin: 'https://www.linkedin.com/in/carrie-song-',
        email: 'carrie.song@stonybrook.edu',
        hobbies: 'Reading, shopping, traveling, and trying new foods, going to concerts',
        funFact: 'I\'ve been to 6 countries',
        personality: '',
        favoriteMemory: 'Secret Santa',
        littleQualities: ''
    },
    'Madison Stone': {
        image: 'brothers/Madison Stone.jpg',
        fullName: 'Madison Stone',
        pledgeClass: 'Omicron',
        graduationDate: 'May 2026',
        major: 'Business Management major with double specialization in Finance and Operations Management. Minor in Theatre Arts',
        bio: 'Hi, I\'m Madison! I\'m passionate about the business side of the entertainment industry. I\'ve served as Recruitment Chair in DSP and currently work in the restaurant industry. I\'ve also completed an internship at The Fashion Foundation. When I\'m not working or studying, I enjoy dancing, pilates, music, and astrology.',
        dspPositions: 'Recruitment Chair (Fall 2024)',
        committees: 'CS, Professional Development (Fall 2025)',
        careerInterests: 'Business side of the entertainment industry',
        pastRoles: 'Waitress at Big Daddy\'s Restaurant (Aug 2023 - Present), Hostess at Big Daddy\'s Restaurant (Jul 2021 - Aug 2023), E-Commerce Intern at The Fashion Foundation (Jan 2025 - Aug 2025), Recruitment Chair at Delta Sigma Pi (Apr 2024 - Dec 2024)',
        linkedin: 'https://www.linkedin.com/in/madison-stone1/',
        email: 'Madison.stone@stonybrook.edu',
        hobbies: 'Dancing, pilates, music, astrology',
        funFact: 'I have a dog named Diggity',
        personality: 'Caring, friendly, creative',
        favoriteMemory: 'Seeing how much all of the brothers want to help each other and genuinely want the best for each other',
        littleQualities: ''
    },
    'Isabelle Baginski': {
        image: 'brothers/Isabelle Baginski.jpg',
        fullName: 'Isabelle Baginski',
        pledgeClass: 'Pi',
        graduationDate: 'May 2026',
        major: 'Applied Mathematics & Statistics and Business Management (Accounting)',
        bio: 'Hi, I\'m Isabelle! I\'m focused on auditing and pursuing my CPA. I\'ve interned at Deloitte as an Audit and Assurance Intern and have a full-time position starting Fall 2026. I\'ve also worked as a Regulatory Compliance Intern at Teachers Federal Credit Union and serve as VP Scholarships & Awards in DSP. When I\'m not auditing or studying, I enjoy tennis, hiking, traveling, pickleball, and going to the beach.',
        dspPositions: 'Recruitment Chair (Spring 2025), VP Scholarships & Awards (25-26)',
        committees: 'CS (Spring 2025)',
        careerInterests: 'Auditing / CPA',
        pastRoles: 'Tennis Coach at Eastern Athletic Club (Jul 2020 - Present), Audit and Assurance Intern at Deloitte (Jun 2025 - Jul 2025), Regulatory Compliance Intern at Teachers Federal Credit Union (Jun 2024 - Aug 2024), Tennis Coach (Freelance) (Jun 2021 - Sep 2023), Personal Shopper at Stop & Shop (Jun 2023 - Aug 2023)',
        linkedin: 'https://www.linkedin.com/in/isabellebaginski',
        email: 'Isabelle.Baginski@stonybrook.edu',
        hobbies: 'Tennis, Hiking, Traveling, Pickleball, Going to the Beach',
        funFact: 'I have scoliosis',
        personality: 'Adventurous, Outgoing, Hardworking',
        favoriteMemory: 'Took a trip to Puerto Rico with some brothers for Spring Break.',
        littleQualities: ''
    },
    'Jaelyn Gunter': {
        image: 'brothers/Jaelyn Gunter.jpeg',
        fullName: 'Jaelyn Gunter',
        pledgeClass: 'Pi',
        graduationDate: 'May 2026',
        major: 'Business Management Specialization in Marketing',
        bio: 'Hi, I\'m Jaelyn! I\'m passionate about social media marketing, especially in the beauty or sports industry. Currently serving as VPCS in DSP, I\'ve also served as Social Media Chair. I work at Ulta as a task associate and had a Marketing internship at The Accredited Group. I also work with College Fashionista, collaborating with brands like Prada, Valentino, and attending New York Fashion Week. When I\'m not creating content or working, I love to travel, watch movies, and try new things!',
        dspPositions: 'Social Media Chair (Spring 2025), VPCS (25-26)',
        committees: 'CS',
        careerInterests: 'Work in social media marketing in either the beauty industry or sports industry',
        pastRoles: 'Vice President of Community Service at Delta Sigma Pi Upsilon Omega (May 2025 - Present), Social Media Chair at Delta Sigma Pi (Dec 2024 - May 2025), Children\'s Party Host at All Sportz Melville (Nov 2024 - Present), Beauty Advisor at Ulta Beauty (Aug 2024 - Present), College Fashionista (Jan 2023 - Present), Marketing Intern at The Accredited Group (Jun 2025 - Aug 2025)',
        linkedin: 'https://www.linkedin.com/in/jaelyn-gunter-9b5935263',
        email: 'jaelyn.gunter@stonybrook.edu',
        hobbies: 'I love to travel, watch movies & try new things!',
        funFact: 'I\'ve been to Puerto Rico more than 10 times',
        personality: 'Passionate, caring & loyal',
        favoriteMemory: 'The day I became a brother ☺️',
        littleQualities: ''
    },
    'Jack Hardiman': {
        image: 'brothers/Jack Hardiman.png',
        fullName: 'Jack Hardiman',
        pledgeClass: 'Pi',
        graduationDate: 'May 2026',
        major: 'Economics & Atmospheric Science',
        bio: 'Hey, I\'m Jack! I\'m interested in energy trading and work as a weather forecaster. I\'ve interned at the Town of Oyster Bay in Emergency Management & Public Safety. When I\'m not forecasting weather or studying economics, I enjoy hiking, cooking, and boxing.',
        dspPositions: 'n/a',
        committees: 'CS',
        careerInterests: 'Energy Trader',
        pastRoles: 'Emergency Management & Public Safety Intern at Town of Oyster Bay (May 2025 - Aug 2025), Weather forecaster',
        linkedin: 'https://www.linkedin.com/in/jackhardiman54',
        email: 'jack.hardiman@stonybrook.edu',
        hobbies: 'Hiking, cooking, boxing',
        funFact: 'I\'ve been to Africa',
        personality: 'Easygoing, nice, good',
        favoriteMemory: 'When Brian Ren and I took on those 2 guys behind the library',
        littleQualities: ''
    },
    'Rashna Kasaju': {
        image: 'brothers/Rashna Kasaju.jpeg',
        fullName: 'Rashna Kasaju',
        pledgeClass: 'Pi',
        graduationDate: 'May 2027',
        major: 'Business Management (Marketing Specialization) and Environmental Design, Policy, and Planning',
        bio: 'Hi, I\'m Rashna! I\'m passionate about digital marketing, marketing, and teaching. Currently serving as PEA in DSP, I\'ve also served as Marketing Chair. I\'ve been working with social media since I was 11 and am a Social Media Creator, Coordinator, and Ambassador on Instagram. I\'ve held various marketing internships and special education roles. When I\'m not creating content or teaching, I enjoy guitar, singing, cooking, baking, video games, pilates, and fitness.',
        dspPositions: 'Marketing Chair (Spring 2025), PEA (Fall 2025)',
        committees: 'Standards (Fall 2025)',
        careerInterests: 'Digital Marketing, Marketing, Teaching',
        pastRoles: 'Social Media Creator, Coordinator, and Ambassador on Instagram (Apr 2017 - Present), Public Relations Officer at Women In Business at Stony Brook University (May 2025 - Present), Fundraising Officer at Women In Business at Stony Brook University (Dec 2024 - May 2025), Social Media and Marketing at Stony Brook University (Aug 2025 - Jan 2026), Undergraduate Teaching Assistant at Stony Brook University (Aug 2025 - Dec 2025), Undergraduate Research Team Leader at Blockchain Business Lab (Jan 2025 - Sep 2025), Special Education Aide (1:1 Support – ESY Program) at Bethpage Union Free School (Jul 2025 - Aug 2025)',
        linkedin: 'https://www.linkedin.com/in/rashna-kasaju',
        email: 'rashna.kasaju@stonybrook.edu',
        hobbies: 'Guitar, singing, cooking, baking, video games, Pilates and fitness',
        funFact: 'I\'ve been working with social media since I was 11!',
        personality: 'Open-minded, ambitious, and creative',
        favoriteMemory: 'Beach cleanups!',
        littleQualities: ''
    },
    'Yuta Kawamura': {
        image: 'brothers/Yuta Kawamura.jpeg',
        fullName: 'Yuta Kawamura',
        pledgeClass: 'Pi',
        graduationDate: 'May 2026',
        major: 'Economics',
        bio: 'Hey, I\'m Yuta! I\'m interested in financial-related fields and have interned at Treasure Data in Marketing. I\'ve served as Alumni Relations Chair in DSP and have experience as a Resident Assistant, Microeconomics Teacher Assistant, and various leadership roles. When I\'m not working or studying, I enjoy football (soccer), poker, and traveling.',
        dspPositions: 'Alumni Relations Chair (Spring 2025)',
        committees: 'AR (Spring 2025)',
        careerInterests: 'Financial related field',
        pastRoles: 'Marketing Intern at Treasure Data (Jun 2025 - Sep 2025), Resident Assistant at SUNY Purchase College (Aug 2023 - May 2024), Microeconomics Teacher Assistant at SUNY Purchase College (Jan 2023 - May 2024), President of International Student Association at SUNY Purchase College (Aug 2022 - May 2024), Student Activities Coordinator - Student Government Association at SUNY Purchase College (Aug 2023 - Dec 2023), Customer Service Representative at JP Alpha Ltd (Jul 2022 - Dec 2022)',
        linkedin: 'https://www.linkedin.com/in/yutak11',
        email: 'yuta.kawamura@stonybrook.edu',
        hobbies: 'Football (not the American one, the true football), poker, Traveling',
        funFact: 'Been to 37 countries',
        personality: '',
        favoriteMemory: '',
        littleQualities: ''
    },
    'Connor Wong': {
        image: 'brothers/Connor Wong.jpeg',
        fullName: 'Connor Wong',
        pledgeClass: 'Pi',
        graduationDate: 'May 2027',
        major: 'Business Major Specializing in Marketing and Finance',
        bio: 'Hi, I\'m Connor! I\'m interested in marketing or finance analytics, administrative roles, or possibly insurance. Currently serving as Chancellor in DSP, I\'ve interned as an Administrative Assistant for the EMS FDNY fundraiser and at David Louie insurance company. I\'m also participating in the Developing Professionals Leveraging Networks Externship at Canon USA. When I\'m not working or studying, I enjoy music, fashion, bouldering, biking, eating, and traveling.',
        dspPositions: 'Chancellor (25-26)',
        committees: 'Professional Development (Spring 2025)',
        careerInterests: 'Marketing or Finance analytics or administrative roles. Possibly insurance.',
        pastRoles: 'Developing Professionals Leveraging Networks Externship at Canon USA (Aug 2025 - Present), Chancellor at Delta Sigma Pi Upsilon Omega (May 2025 - Present), Ice Cream Shop Associate at Le Mer (Jul 2025 - Aug 2025), Summer Intern at EMS FDNY Help Fund (May 2024 - Jul 2024), Office Assistant at P/Kaufmann Contract (Aug 2023), Administrative Assistant Intern for EMS FDNY fundraiser, Intern at David Louie insurance company',
        linkedin: 'https://www.linkedin.com/in/connor-wong1',
        email: 'connor.wong@stonybrook.edu',
        hobbies: 'Music, fashion, bouldering, biking, eating, traveling',
        funFact: 'Traveled four countries in one month!',
        personality: '',
        favoriteMemory: '',
        littleQualities: ''
    },
    'Samuel Zou': {
        image: 'brothers/Samuel Zou.jpeg',
        fullName: 'Samuel Zou',
        pledgeClass: 'Pi',
        graduationDate: 'May 2027',
        major: 'Applied Mathematics & Statistics / Economics',
        bio: 'Hey, I\'m Samuel! I\'m passionate about actuarial work, data analytics, and financial analytics. Currently serving as VPF in DSP, I\'ve also served as Philanthropy Chair. I work as an Administrative Assistant at a non-profit organization (AWCWA) and as a Data & Financial Analytics Researcher. When I\'m not analyzing data or working on financial models, I enjoy cooking, arts & crafts, concerts, billiards, and music.',
        dspPositions: 'Philanthropy Chair (Spring 2025), VPF (25-26)',
        committees: 'AR/Professional Development, Philanthropy (Spring 2025)',
        careerInterests: 'Actuary, Data Analytics, Financial Analytics',
        pastRoles: 'Vice President of Finance at Delta Sigma Pi Upsilon Omega (May 2025 - Present), Philanthropy Chairperson at Delta Sigma Pi (Dec 2024 - May 2025), Administrative Assistant at ASSOCIATION OF WOMEN CONSTRUCTION WORKERS OF AMERICA INC (Jul 2024 - Aug 2024), Data & Financial Analytics Researcher',
        linkedin: 'https://www.linkedin.com/in/samuel-zou',
        email: 'samuel.zou@stonybrook.edu',
        hobbies: 'Cooking, Arts & Crafts, Concerts, Billiards, and Music',
        funFact: 'I\'m allergic to peanuts but I love eating peanut butter noodles.',
        personality: 'Chill, Hardworking, Funny',
        favoriteMemory: 'Semi-Formal',
        littleQualities: ''
    },
    'Steven Ye': {
        image: 'brothers/Steven Ye.jpeg',
        fullName: 'Steven Ye',
        pledgeClass: 'Rho',
        graduationDate: 'May 2027',
        major: 'Applied Mathematics & Statistics / Economics',
        bio: 'Hey, I\'m Steven! I\'m interested in finance and currently serve as Alumni Chair in DSP. I work as an Audio Visual Technician at SBU and have experience as a Residential Fitness Center Manager and Monitor. When I\'m not working or studying, I enjoy hanging out with friends and sleeping.',
        dspPositions: 'Alumni Chair (Fall 2025)',
        committees: 'Professional Development/AR (Fall 2025)',
        careerInterests: 'Finance',
        pastRoles: 'Audio Visual Technician at Stony Brook University (Oct 2025 - Present), Alumni Chair at Delta Sigma Pi (Aug 2025 - Present), Residential Fitness Center Manager at Stony Brook University (Oct 2024 - Jun 2025), Residential Fitness Center Monitor at Stony Brook University (Sep 2024 - Oct 2024), Warehouse Staff at Stony Brook University (Apr 2024 - Sep 2024), Tutor at SMITH Preparatory (Jan 2023 - May 2023), Dietary Aid at Dry Harbors Nursing Home (Jun 2022 - Aug 2022)',
        linkedin: 'https://www.linkedin.com/in/steven-ye7/',
        email: 'steven.ye@stonybrook.edu',
        hobbies: 'Hanging out with friends and sleeping',
        funFact: 'Aldo\'s my twin',
        personality: 'Cool',
        favoriteMemory: 'Semi-Formal',
        littleQualities: ''
    },
    'Charleen You': {
        image: 'brothers/Charleen You.jpeg',
        fullName: 'Charleen You',
        pledgeClass: 'Rho',
        graduationDate: 'May 2027',
        major: 'Business Management Specializing in Operations and Marketing',
        bio: 'Hi, I\'m Charleen! I\'m passionate about HR or Marketing and currently serve as VPCO in DSP. I\'ve interned in HR at Financial Payability and work as a Student Tech at DoIT client support. When I\'m not working or studying, I enjoy traveling, matcha cafe hopping, and watching movies.',
        dspPositions: 'VPCO (25-26)',
        committees: 'n/a',
        careerInterests: 'HR or Marketing',
        pastRoles: 'Secretary (Vice Chapter of Operations) at Delta Sigma Pi Upsilon Omega (May 2025 - Present), Client Support Student Technician at Stony Brook University (May 2024 - Present), Student Technician at Stony Brook University (Jan 2024 - May 2024), Human Resources Intern at Paybility Financial (Jan 2025 - Apr 2025), Admissions Assistant at University of Connecticut (May 2023 - Jun 2023)',
        linkedin: 'https://www.linkedin.com/in/charleen-you/',
        email: 'charleen.you@stonybrook.edu',
        hobbies: 'Traveling, Matcha cafe hopping, and watching movies',
        funFact: '',
        personality: 'Bubbly, curious, and optimistic',
        favoriteMemory: 'Taking the same classes with brothers and being able to work on group projects',
        littleQualities: ''
    },
    'Hannah Kim': {
        image: 'brothers/Hannah Kim.jpeg',
        fullName: 'Hannah Kim',
        pledgeClass: 'Rho',
        graduationDate: 'May 2027',
        major: 'Business Management, Specialization: Finance',
        bio: 'Hi, I\'m Hannah! I\'m passionate about Human Resources and currently serve as Marketing Chair in DSP. I\'m interning at The Peninsula New York (Hotel/Hospitality field) as an HR Intern. When I\'m not working or studying, I enjoy shopping, attending concerts, and going out in the city.',
        dspPositions: 'Marketing Chair (Fall 2025)',
        committees: 'n/a',
        careerInterests: 'Human Resources',
        pastRoles: 'People and Culture Intern at The Peninsula Hotels (Jun 2025 - Present)',
        linkedin: 'https://www.linkedin.com/in/hannah-kim5275',
        email: 'hannah.h.kim@stonybrook.edu',
        hobbies: 'Shopping, attending concerts, and going out in the city',
        funFact: 'I eat spicy wontons three times a week',
        personality: 'Outgoing, sociable, friendly',
        favoriteMemory: 'Formal last Spring of 2025 after I crossed. I had such a fun time with my class and brothers overall.',
        littleQualities: ''
    },
    'Anna Lin': {
        image: 'brothers/Anna Lin.JPG',
        fullName: 'Anna Lin',
        pledgeClass: 'Rho',
        graduationDate: 'May 2027',
        major: 'Business Management, specialization: marketing and operations management with a minor in real estate and insurance',
        bio: 'Hi, I\'m Anna! I\'m passionate about Product Management, Product Marketing and Advertisement, and Operations Analyst roles. Currently serving as Alumni Relations Chair in DSP, I work as a Student Technician at DoIT and serve as Public Relations Director & Fundraising Chair at Fujianese Culture Club. I\'m also a Scholars Mentor at University Scholars College. When I\'m not working or studying, I enjoy sports (Soccer, Pickleball, Volleyball), listening to music, and hanging out with friends.',
        dspPositions: 'Alumni Relations Chair (Spring 2026)',
        committees: 'AR/Philanthropy (Fall 2025)',
        careerInterests: 'Product Management, Product Marketing and Advertisement, Operations Analyst',
        pastRoles: 'Student Technician at Stony Brook University (May 2025 - Present), Student Technician Intern at Stony Brook University (Feb 2025 - May 2025), General Manager at New Mun Yuen Restaurant (Sep 2017 - Present), Public Relations Director at Fujianese Culture Club (Jan 2024 - May 2025), Student Assistant at Stony Brook University (Aug 2024 - Dec 2024), Summer Intern at Liberty Arts Academy (May 2024 - Jul 2024), Scholars Mentor at University Scholars College',
        linkedin: 'https://www.linkedin.com/in/annalin88',
        email: 'anna.lin.2@stonybrook.edu',
        hobbies: 'Sports (Soccer, Pickleball, Volleyball), listening to music, hanging out with friends',
        funFact: 'I have 5 siblings',
        personality: 'Spontaneous, Funny, Chill',
        favoriteMemory: 'Crossing with my class',
        littleQualities: ''
    },
    'Siena Rahman': {
        image: 'brothers/Siena Rahman.jpeg',
        fullName: 'Siena Rahman',
        pledgeClass: 'Rho',
        graduationDate: 'May 2027',
        major: 'Information Systems: Finance; Applied Mathematics & Statistics',
        bio: 'Hi, I\'m Siena! I\'m passionate about Data Analytics and Data Science. Currently serving as Webmaster in DSP, I\'m an AI/ML Fellow at Cornell Tech and work as a Resident Assistant at SBU. I have an incoming position in Supply Chain Analytics at Zebra Technologies and past experience as a Computational Math Researcher at FSU. When I\'m not analyzing data or researching, I enjoy thrifting, painting, makeup, anime, and creating IG Reels + TikTok content.',
        dspPositions: 'Webmaster (Fall 2025)',
        committees: 'Professional Development (Fall 2025)',
        careerInterests: 'Data Analyst/Scientist',
        pastRoles: 'AI/ML Fellow at Break Through Tech (May 2025 - Present), AI Studio Fellow at Nestlé (Aug 2025 - Dec 2025), Registration Workshop Assistant at Stony Brook University (Jun 2024 - Aug 2025), Probability & Statistics Teaching Assistant at Stony Brook University (Jan 2025 - May 2025), Undergraduate Research Assistant at FSU Department of Mathematics (May 2025 - Jul 2025), Resident Assistant at SBU, Incoming Supply Chain Analytics at Zebra Technologies',
        linkedin: 'https://www.linkedin.com/in/sienarahman/',
        email: 'siena.rahman@stonybrook.edu',
        hobbies: 'Thrifting, Painting, Makeup, Anime, IG Reels + TikTok 🥀',
        funFact: 'I have 16 piercings ⛓️‍💥',
        personality: 'Silly, Outgoing, Cheerful',
        favoriteMemory: 'Recruitment',
        littleQualities: ''
    },
    'Waylene Hui': {
        image: 'brothers/Waylene Hui.jpeg',
        fullName: 'Waylene Hui',
        pledgeClass: 'Rho',
        graduationDate: 'May 2027',
        major: 'Applied Mathematics and Statistics',
        bio: 'Hi, I\'m Waylene! I currently serve as DEI Chair in DSP and am involved in Professional Development. I\'ve interned at the International Rescue Committee and have experience as a Policy Intern at Coalition for Asian American Children and Families and Development Intern at Apex for Youth.',
        dspPositions: 'DEI Chair (Fall 2025)',
        committees: 'Professional Development (Fall 2025)',
        careerInterests: '',
        pastRoles: 'Intern at International Rescue Committee (Jun 2025 - Present), Policy Intern at Coalition for Asian American Children and Families (Jul 2023 - Aug 2023), Development Intern at Apex for Youth (Jul 2023 - Aug 2023), Apex for Youth Ambassador (Nov 2021 - Jun 2023)',
        linkedin: 'https://www.linkedin.com/in/waylene-hui/',
        email: 'waylene.hui@stonybrook.edu',
        hobbies: '',
        funFact: '',
        personality: '',
        favoriteMemory: '',
        littleQualities: ''
    },
    'Luke Alexander': {
        image: 'brothers/Luke Alexander.jpeg',
        fullName: 'Luke Alexander',
        pledgeClass: 'Rho',
        graduationDate: 'May 2027',
        major: 'Accounting',
        bio: 'Hey, I\'m Luke! I\'m focused on getting my CPA and currently serve in Philanthropy/CS in DSP. I had a 1-month internship abroad in Muscat, Oman as a Risk Consultant Intern at the Performance Factory. When I\'m not studying accounting or working, I enjoy playing guitar, piano, volleyball, making beats, and listening to music.',
        dspPositions: 'n/a',
        committees: 'Philanthropy/CS (Fall 2025)',
        careerInterests: 'Get my CPA',
        pastRoles: 'Strategy Consulting Intern at the Performance Factory (PerFact) (Dec 2024 - Apr 2025), Risk Consultant Intern in Muscat, Oman',
        linkedin: 'https://www.linkedin.com/in/luke-alexander123',
        email: 'luke.alexander@stonybrook.edu',
        hobbies: 'I play guitar, piano, vball, make beats, listening to music',
        funFact: 'The producer FNZ who co-produced hits like L$D, first person shooter, what did I miss, donda, and purity actually liked one of my beats on instagram',
        personality: 'Go with the flow',
        favoriteMemory: 'My initiation',
        littleQualities: ''
    },
    'Feyintoluwa Bolaji': {
        image: 'brothers/Tolu B.jpeg',
        fullName: 'Feyintoluwa Bolaji',
        pledgeClass: 'Rho',
        graduationDate: 'May 2027',
        major: 'Business Management/Accounting/Finance',
        bio: 'Hey, I\'m Feyintoluwa! I\'m passionate about accounting and currently serve as Recruitment Chair and Social Chair in DSP. I work as a Fitness Monitor and Intramural Official at SBU, and have experience as a Sales Associate at PetSmart. When I\'m not working or studying, I enjoy basketball, music, food, video games, art, and cars.',
        dspPositions: 'Recruitment Chair (Fall 2025), Social Chair (Spring 2026)',
        committees: 'Philanthropy (Fall 2025)',
        careerInterests: 'Accounting',
        pastRoles: 'Fitness Monitor at Stony Brook University (Jan 2026 - Present), Intramural Official at Stony Brook University (Oct 2025 - Present), Active Brother at Delta Sigma Pi Upsilon Omega (Apr 2025 - Present), Sales Associate at PetSmart (Jul 2025 - Dec 2025)',
        linkedin: 'https://www.linkedin.com/in/feyintoluwa-bolaji',
        email: 'Feyintoluwa.bolaji@stonybrook.edu',
        hobbies: 'Basketball, Music, Food, Video Games, Art, Cars',
        funFact: 'My Spotify Playlist is 7,000+ songs',
        personality: '',
        favoriteMemory: 'Formal',
        littleQualities: ''
    },
    'Henry Cai': {
        image: 'brothers/Henry Cai.jpeg',
        fullName: 'Henry Cai',
        pledgeClass: 'Rho',
        graduationDate: 'May 2027',
        major: 'Applied Mathematics & Statistics / Economics',
        bio: 'Hey, I\'m Henry! I\'m passionate about actuarial work and data analytics. Currently serving as Social Chair in DSP, I work as a Fitness Monitor at SBU and have experience in Data Analytics Research and as a Data Management Intern at FDNY. When I\'m not analyzing data or working out, I enjoy volleyball, billiards, ping pong, handball, raving, concerts, and fashion.',
        dspPositions: 'Social Chair (Fall 2025)',
        committees: 'Professional Development/Philanthropy (Fall 2025)',
        careerInterests: 'Actuary/Data',
        pastRoles: 'Fitness Monitor at Stony Brook University (Jan 2025 - Present), Sales Associate at CrunCheese (May 2023 - Aug 2023), Administrative Assistant at New York City Fire Department (Jun 2022 - Aug 2022), Data Analytics Research, Data Management Intern at FDNY',
        linkedin: 'https://www.linkedin.com/in/henry-cai-/',
        email: 'henry.cai@stonybrook.edu',
        hobbies: 'Volleyball, Billiards, Ping Pong, Handball, Raving, Concerts, Fashion',
        funFact: 'I can eat mala everyday',
        personality: 'Outgoing, compassionate, responsible',
        favoriteMemory: 'Formal',
        littleQualities: ''
    },
    'Alex Chan': {
        image: 'brothers/Alex Chan.jpg',
        fullName: 'Alex Chan',
        pledgeClass: 'Rho',
        graduationDate: 'May 2027',
        major: 'Applied Mathematics and Statistics + Information System Major + Finance Minor',
        bio: 'Hey, I\'m Alex! I currently serve as Recruitment Chair in DSP and am involved in Standards. I work as a Student Technician Intern at SBU and have experience as Warehouse Staff and as a Portfolio Analyst Intern at NYC Department of Housing Preservation & Development.',
        dspPositions: 'Recruitment Chair (Fall 2025)',
        committees: 'Standards (Fall 2025)',
        careerInterests: '',
        pastRoles: 'Student Technician Intern at Stony Brook University (Feb 2025 - Present), Warehouse Staff at Stony Brook University (Apr 2024 - Feb 2025), Portfolio Analyst Intern at NYC Department of Housing Preservation & Development (Jul 2025 - Aug 2025)',
        linkedin: 'https://www.linkedin.com/in/alex-chan-/',
        email: 'alex.chan@stonybrook.edu',
        hobbies: '',
        funFact: '',
        personality: '',
        favoriteMemory: '',
        littleQualities: ''
    },
    'Walter Benitez': {
        image: 'brothers/Walter.jpeg',
        fullName: 'Walter Benitez',
        pledgeClass: 'Sigma',
        graduationDate: 'May 2028',
        major: 'Economics, Minor in Applied Math & Statistics',
        bio: 'Hey, I\'m Walter! I\'m interested in working with Government and Policy. Currently serving as DEI Chair in DSP, I\'m a Wearable Futures Research Assistant, Blockchain Business Lab VIP member, and Stony Brook URECA Explorations in STEM participant. When I\'m not researching or studying, I enjoy fishing, hanging by a body of water, and I want to learn to skateboard and play the guitar. I tend to watch Pixar movies when I study.',
        dspPositions: 'DEI Chair (Spring 2026)',
        committees: 'Professional Development',
        careerInterests: 'Interested in working with Government and Policy',
        pastRoles: 'Active Member at Delta Sigma Pi Upsilon Omega (Oct 2025 - Present), Undergraduate Research Assistant - Blockchain Business Lab at Stony Brook University College of Business (Aug 2025 - Present), Undergraduate Research Assistant - Comparative Analysis of Textile Waste Policy at Stony Brook University College of Engineering and Applied Sciences (May 2025 - Present), Climate Reality Training, 2024 US Training Mentor at The Climate Reality Project (Apr 2024 - Jul 2025), Stony Brook Simons STEM Scholars Program - Summer Bridge (Jun 2024 - Aug 2024)',
        linkedin: 'https://www.linkedin.com/in/walter-jacob-benitez-481529332/',
        email: 'benitez.walter@stonybrook.edu',
        hobbies: 'I like fishing and hanging by a body of water, and I want to learn to skateboard and play the guitar. I tend to watch pixar movies when I study.',
        funFact: 'I have 40+ chickens and 4 cats',
        personality: 'Unserious but serious',
        favoriteMemory: 'Anytime we get food',
        littleQualities: ''
    },
    'Jenny Chen': {
        image: 'brothers/Jenny Chen.jpeg',
        fullName: 'Jenny Chen',
        pledgeClass: 'Sigma',
        graduationDate: 'May 2027',
        major: 'Business Management: Operations, Psychology double major',
        bio: 'Hi, I\'m Jenny! I\'m passionate about Human Resources and currently serve as Recruitment Chair in DSP. I work as an Administrative & Communications Intern at CAS Dean\'s Office and as a Clinical Operations Student Assistant at Stony Brook School of Dental Medicine. When I\'m not working or studying, I enjoy strength training, collecting jewelry, and listening to music.',
        dspPositions: 'Recruitment Chair (Spring 2026)',
        committees: 'Community Service, Philanthropy (Spring 2026)',
        careerInterests: 'Human Resources',
        pastRoles: 'Recruitment Chair at Delta Sigma Pi Upsilon Omega (Dec 2025 - Present), Active Member at Delta Sigma Pi (Oct 2025 - Present), Clinical Operations Student Assistant at Stony Brook School of Dental Medicine (Sep 2025 - Present), Administrative and Communications Intern at Stony Brook University College of Arts and Sciences (Oct 2024 - Present), Cashier at Cross Island Fruit (Jul 2022 - Present), Waitress at Difference Chinese Restaurant (Jan 2017 - Present)',
        linkedin: 'https://www.linkedin.com/in/jennychen8865',
        email: 'jenny.chen.12@stonybrook.edu',
        hobbies: 'Strength training, collecting jewelry, listening to music',
        funFact: 'I lived in China for 5 years',
        personality: 'Thoughtful, ambitious, dependable',
        favoriteMemory: 'Homecoming',
        littleQualities: ''
    },
    'Claudelle Cortez': {
        image: 'brothers/Claudelle Justene Cortez.heic',
        fullName: 'Claudelle Cortez',
        pledgeClass: 'Sigma',
        graduationDate: 'May 2027',
        major: 'Economics',
        bio: 'Hi, I\'m Claudelle! I want to work with finance or data analytics in the entertainment industry, specifically music! My dream is to work at Spotify. Currently serving as Social Media Chair in DSP, I\'m also the Social Activities Chair for Women in Business at Stony Brook. I currently work at Shake Shack and I used to be a tennis camp coach in high school. When I\'m not working or studying, I love to journal, play tennis, read, write (mostly short stories), thrifting, and listening to music!',
        dspPositions: 'Social Media Chair (Spring 2026)',
        committees: 'Philanthropy (Spring 2026)',
        careerInterests: 'I want to work with finance or data analytics in the entertainment industry, specifically music! My dream is to work at Spotify :)',
        pastRoles: 'Social Activities Chair at Women In Business at Stony Brook University (May 2025 - Present), Food Service Worker at Shake Shack (Jun 2022 - Present), Carle Place Tennis Camp Coach at Carle Place Middle Senior High School (Jun 2023 - Jul 2023)',
        linkedin: 'https://www.linkedin.com/in/claudelle-cortez-a83199355',
        email: 'claudellejuste.cortez@stonybrook.edu',
        hobbies: 'I love to journal, play tennis, read, write (mostly short stories), thrifting, and listening to music!',
        funFact: 'I played the violin for 10 years!',
        personality: 'Curious, Empathetic, and Compassionate',
        favoriteMemory: 'Staying up late to bake for our fundraiser or homecoming!',
        littleQualities: ''
    },
    'Natsumi Ekanayaka': {
        image: 'brothers/Natsumi Ekanayaka.jpeg',
        fullName: 'Natsumi Ekanayaka',
        pledgeClass: 'Sigma',
        graduationDate: 'May 2028',
        major: 'B.S. in Business Management (Marketing)',
        bio: 'Hi, I\'m Natsumi! I\'m passionate about Marketing and Entrepreneurship. I\'ve worked as a Management Assistant at TOCO International Export Company and have been an Active Volunteer at NPO法人チャイルドドクター・ジャパン (NPO Child Doctor Japan). When I\'m not working or studying, I love to read, watch movies, play the piano + guitar, and shop at malls.',
        dspPositions: 'n/a',
        committees: 'n/a',
        careerInterests: 'Marketing/Entrepreneurship',
        pastRoles: 'Management Assistant at Toco International (Pvt) Ltd (Jun 2024 - Aug 2024), Active Volunteer at NPO法人チャイルドドクター・ジャパン (NPO Child Doctor Japan) (Aug 2023 - Aug 2024)',
        linkedin: 'https://www.linkedin.com/in/Natsumi-E',
        email: 'natsumi.ekanayaka@stonybrook.edu',
        hobbies: 'I love to read, watch movies, play the piano + guitar, and shop at malls',
        funFact: 'I love the color pink',
        personality: 'Thoughtful, adaptable, warm',
        favoriteMemory: 'Pledge process + initiation!',
        littleQualities: ''
    },
    'Joshua Jacob': {
        image: 'brothers/Joshua Jacob.jpeg',
        fullName: 'Joshua Jacob',
        pledgeClass: 'Sigma',
        graduationDate: 'May 2027',
        major: 'Computer Science & Economics',
        bio: 'Hey, I\'m Joshua! I\'m passionate about technology and data. I\'ve served as Public Relations Manager at Web Development Club of Stony Brook University and have been a Software Engineering Mentee at Google. I\'ve also worked as a Data Analyst Intern at Veolia North America and as an Undergraduate Research Team Leader at Blockchain Business Lab.',
        dspPositions: 'n/a',
        committees: 'n/a',
        careerInterests: '',
        pastRoles: 'Public Relations Manager at Web Development Club of Stony Brook University (May 2025 - Present), Representative at Web Development Club of Stony Brook University (Sep 2024 - Apr 2025), Software Engineering Mentee at Google (Jun 2025 - Sep 2025), Data Analyst Intern at Veolia North America (May 2025 - Aug 2025), Undergraduate Research Team Leader at Blockchain Business Lab (Jan 2025 - May 2025)',
        linkedin: 'https://www.linkedin.com/in/joshuasunnyjacob/',
        email: 'joshua.s.jacob@stonybrook.edu',
        hobbies: '',
        funFact: '',
        personality: '',
        favoriteMemory: '',
        littleQualities: ''
    },
    'James Kyung': {
        image: 'brothers/James Kyung.jpeg',
        fullName: 'James Kyung',
        pledgeClass: 'Sigma',
        graduationDate: 'May 2027',
        major: 'Business Management',
        bio: 'Hey, I\'m James! I currently serve as Webmaster in DSP. I\'m a Tax Intern at Forvis Mazars US (Incoming Spring 2027) and at Strategic Financial & Tax Planning Services (Incoming Spring 2026). I\'m also a Senior Analyst at Fourier Fund of Stony Brook University and have experience as an Audit Intern at Skinnon & Faber and as a Campus Tour Guide at Stony Brook University.',
        dspPositions: 'Webmaster (Spring 2026)',
        committees: '',
        careerInterests: '',
        pastRoles: 'Tax Intern at Forvis Mazars US (Oct 2025 - Present, Incoming Spring 2027), Tax Intern at Strategic Financial & Tax Planning Services (Oct 2025 - Present, Incoming Spring 2026), Senior Analyst at Fourier Fund of Stony Brook University (Oct 2024 - Present), Audit Intern at Skinnon & Faber (Feb 2025 - Aug 2025), Campus Tour Guide at Stony Brook University (Sep 2023 - Dec 2024)',
        linkedin: 'https://www.linkedin.com/in/jameskyung/',
        email: 'james.kyung@stonybrook.edu',
        hobbies: '',
        funFact: '',
        personality: '',
        favoriteMemory: '',
        littleQualities: ''
    },
    'Ashley Lee': {
        image: 'brothers/Ashley Lee.jpeg',
        fullName: 'Ashley Lee',
        pledgeClass: 'Sigma',
        graduationDate: 'May 2028',
        major: 'Business Management',
        bio: 'Hi, I\'m Ashley! I\'m interested in accounting/finance and currently serve as Social Chair in DSP. I\'m also Merch Chair at Women In Business at Stony Brook University and a Welcoming Team Member at Korean Christian Fellowship. I\'ve worked as a Senior Customer Service Representative at Enterprise Mobility and served as RHA Gray Hall Senator at Stony Brook University.',
        dspPositions: 'Social Chair (Spring 2026)',
        committees: 'PDC, Philanthropy (Spring 2026)',
        careerInterests: 'Accounting/finance',
        pastRoles: 'Social Chair at Delta Sigma Pi (Dec 2025 - Present), Member at Delta Sigma Pi (Oct 2025 - Present), Merch Chair at Women In Business at Stony Brook University (Nov 2025 - Present), Member at Women In Business at Stony Brook University (Oct 2024 - Present), Welcoming Team Member at Korean Christian Fellowship (Aug 2025 - Present), Senior Customer Service Representative at Enterprise Mobility (May 2025 - Oct 2025), RHA Gray Hall Senator at Stony Brook University (Jan 2025 - May 2025)',
        linkedin: 'https://www.linkedin.com/in/ashleyjalee',
        email: 'ashley.lee.1@stonybrook.edu',
        hobbies: 'Gym, handball, going to the city, baking',
        funFact: 'I\'ve fractured my finger twice, both from football',
        personality: 'Spontaneous, active, foodie',
        favoriteMemory: 'Pledging, hoco, and semis',
        littleQualities: ''
    },
    'Aldo Ramirez': {
        image: 'brothers/Aldo_Ramirez.jpg',
        fullName: 'Aldo Ramirez',
        pledgeClass: 'Sigma',
        graduationDate: 'May 2027',
        major: 'Business Management: Operations, Accounting Minor',
        bio: 'Hey, I\'m Aldo! I\'m passionate about Accounting, CPA, and HR. Currently serving as Philanthropy Chair in DSP, I\'m involved in the VITA Program. I work as a Team Leader at Chick-fil-A Restaurants and have experience as a Fulfillment Expert at Target and as a Crew Member at Philly Pretzel Factory. When I\'m not working or studying, I enjoy running, soccer, volleyball, sports, and music.',
        dspPositions: 'Philanthropy Chair (Spring 2026)',
        committees: 'Philanthropy',
        careerInterests: 'Accounting, CPA, HR',
        pastRoles: 'Philanthropy Chairperson at Delta Sigma Pi Upsilon Omega (Dec 2025 - Present), Active Member at Delta Sigma Pi (Oct 2025 - Present), Team Leader at Chick-fil-A Restaurants (Jun 2024 - Present), Fulfillment Expert at Target (Nov 2022 - Dec 2024), Crew Member at Philly Pretzel Factory (Oct 2021 - May 2022), VITA Program',
        linkedin: 'https://www.linkedin.com/in/aldramirez',
        email: 'aldo.ramirez@stonybrook.edu',
        hobbies: 'Running, Soccer, Volleyball, Sports, Music',
        funFact: 'I\'ve run 2 marathons so far. I love listening to new music',
        personality: '',
        favoriteMemory: 'Hoco',
        littleQualities: ''
    },
    'Jahzeel Requena': {
        image: 'brothers/Jahzeel Requena.jpeg',
        fullName: 'Jahzeel Requena',
        pledgeClass: 'Sigma',
        graduationDate: 'May 2028',
        major: 'Technological Systems Management',
        bio: 'Hey, I\'m Jahzeel! I\'m passionate about Project Management. I work as a Student Technician for DoIT, Residential Ambassador for Pre-College Summer Program, and Student Assistant for the Director of Pre-College Summer Program. I also have experience as an AV Technician at Bronx Seventh Day Adventist Church. When I\'m not working or studying, I enjoy videogames, reading, writing, listening to music, and basketball.',
        dspPositions: 'n/a',
        committees: 'Community Service, Alumni Relations (Spring 2026)',
        careerInterests: 'Project management',
        pastRoles: 'Student Technician at Stony Brook University (Mar 2025 - Present), Residential Ambassador at Stony Brook University (Jun 2025 - Jul 2025), Intern Student Technician at Stony Brook University (Feb 2025 - May 2025), AV Technician at Bronx Seventh Day Adventist Church (Feb 2022 - Jul 2024)',
        linkedin: 'https://www.linkedin.com/in/jahzeel-requena',
        email: 'jahzeel.requena@stonybrook.edu',
        hobbies: 'Videogames, reading, writing, listening to music, and basketball',
        funFact: 'I have a brown belt in karate',
        personality: 'Swag, calm, agreeable',
        favoriteMemory: 'Homecoming',
        littleQualities: ''
    },
    'Reon Sarkar': {
        image: 'brothers/Reon Sarkar.jpeg',
        fullName: 'Reon Sarkar',
        pledgeClass: 'Sigma',
        graduationDate: 'May 2028',
        major: 'Technological Systems Management Specializing in ISE',
        bio: 'Hey, I\'m Reon! I\'m interested in IT, Tech, and Consulting. I\'ve worked as a Network Operations Intern at Spellman High Voltage and currently work as a Sales Advisor at Best Buy. I also have experience as an Usher at Island 16 Cinema De Lux and as a Crew Member at Domino\'s Pizza. When I\'m not working or studying, I enjoy video games, TV shows, cooking, and working out.',
        dspPositions: 'n/a',
        committees: 'Professional Development, Community Service, Philanthropy (Spring 2026)',
        careerInterests: 'IT, Tech, Consulting',
        pastRoles: 'Sales Advisor at Best Buy (Sep 2025 - Present), Usher at Island 16 Cinema De Lux (Sep 2023 - Sep 2025), Network Operations Intern at Spellman High Voltage Electronics Corporation (Jun 2025 - Aug 2025), Crew Member at Domino\'s Pizza (Jan 2024 - May 2024)',
        linkedin: 'https://www.linkedin.com/in/reon-sarkar',
        email: 'reon.sarkar@stonybrook.edu',
        hobbies: 'Video Games, tv shows, cooking, working out',
        funFact: 'I was bit by a cobra',
        personality: '',
        favoriteMemory: 'Homecoming',
        littleQualities: ''
    },
    'William Sim': {
        image: 'brothers/William Sim.jpeg',
        fullName: 'William Sim',
        pledgeClass: 'Sigma',
        graduationDate: 'May 2027',
        major: 'Business Management & Marketing',
        bio: 'Hey, I\'m William! I currently serve as Marketing Chair in DSP. I\'m an Incoming Design Management Intern at Warner Bros. Discovery and work as a Graphic Designer - Esports and Creative Content – SBU Athletics Student Assistant at Stony Brook University. I also work as a Graphic Designer at Rosewood Creative, FaZe Clan, and NRG Esports.',
        dspPositions: 'Marketing Chair (Spring 2026)',
        committees: '',
        careerInterests: '',
        pastRoles: 'Incoming Design Management Intern at Warner Bros. Discovery (Dec 2025 - Present), Graphic Designer - Esports at Stony Brook University (Sep 2025 - Present), Creative Content – SBU Athletics Student Assistant at Stony Brook University (Sep 2025 - Present), Graphic Designer at Rosewood Creative (Aug 2024 - Present), Graphic Designer at FaZe Clan (May 2024 - Present), Graphic Designer at NRG Esports (Nov 2022 - Aug 2024)',
        linkedin: 'https://www.linkedin.com/in/williamsimjr/',
        email: 'william.sim@stonybrook.edu',
        hobbies: '',
        funFact: '',
        personality: '',
        favoriteMemory: '',
        littleQualities: ''
    },
    'Jaden Yang': {
        image: 'brothers/Jaden Yang.JPG',
        fullName: 'Jaden Yang',
        pledgeClass: 'Sigma',
        graduationDate: 'May 2028',
        major: 'Applied Mathematics & Statistics',
        bio: 'Hey, I\'m Jaden! I\'m interested in Actuary, Accounting, Data, Finance, Operations, and Consulting. I work as a DoIT Client Support Technician/Assistant Project Manager and serve as Korean Student Association Historian. I also work as a Mathematics Tutor (Freelance) and have experience as an Assistant Manager at Bounce! Trampoline Park, Member Services Associate at Life Time Inc., and Hospitality Professional at Chick-fil-A Restaurants.',
        dspPositions: 'n/a',
        committees: 'n/a',
        careerInterests: 'Actuary, Accounting, Data, Finance, Operations, Consulting',
        pastRoles: 'Client Support Assistant Project Manager at Stony Brook University (Sep 2025 - Present), Client Support Technician at Stony Brook University (May 2025 - Present), IT Technician Intern at Stony Brook University (Jan 2025 - May 2025), Mathematics Tutor (Freelance) (Aug 2022 - Present), Assistant Manager at Bounce! Trampoline Park (Dec 2023 - Aug 2024), Member Services Associate at Life Time Inc. (Dec 2022 - Dec 2023), Hospitality Professional at Chick-fil-A Restaurants (Mar 2022 - Nov 2022), Korean Student Association Historian',
        linkedin: 'https://www.linkedin.com/in/jadenyngg/',
        email: 'jaden.yang@stonybrook.edu',
        hobbies: 'Basketball, weightlifting, fashion, shopping, photography, music, cats, cars, good food, video games',
        funFact: 'I used to produce music',
        personality: 'Compassionate, ambitious, chill',
        favoriteMemory: 'Homecoming with the brothers',
        littleQualities: ''
    }
};

