// Brothers profile data
const brothersData = {
    'Aidan Chan': {
        image: 'brothers/Aidan Chan.jpg',
        fullName: 'Aidan Chan',
        pledgeClass: 'Rho',
        graduationDate: 'May 2027',
        major: 'Business Mgmt (Finance)',
        bio: 'Hey, I\'m Aidan. Started cutting hair for friends in my dorm room and it turned into Herb Fades—now I\'m serving 150+ clients on campus. I like seeing how a good cut can change someone\'s confidence. When I\'m not cutting hair or studying, I\'m usually playing basketball or grabbing food with friends.',
        dspPositions: '',
        committees: 'Philanthropy (Fall 2025)',
        careerInterests: 'Financial Analyst, Starting and owning my own barbershop',
        pastRoles: 'Founder at Herb Fades (Dec 2022 - Present), Food Server at Luigi\'s Restaurant & Bar (Jul 2022 - Aug 2023), Customer Service Representative at eFresh (Jul 2020 - Oct 2021)',
        linkedin: 'https://www.linkedin.com/in/aidanchan27',
        email: 'aidan.chan@stonybrook.edu',
        hobbies: 'Basketball, eating, playing games',
        funFact: 'I am recently bilingual',
        personality: 'Smile, outgoing, chill',
        favoriteMemory: 'Baking and playing games with my fellow brothers',
        littleQualities: ''
    },
    'Ana Jiang': {
        image: 'brothers/Ana Jiang.jpeg',
        fullName: 'Ana Jiang',
        pledgeClass: 'Rho',
        graduationDate: 'May 2027',
        major: 'Business Mgmt (Operations), Minor in Accounting',
        bio: 'Hey, I\'m Ana! I love bringing people together and helping them find opportunities that actually fit. Whether I\'m organizing events or working in HR, I\'m all about solving problems and making things work better. Currently serving as Philanthropy Chair, I\'ve also worked at the Career Center and Fourier Fund. When I\'m not working or studying, you\'ll find me hiking, traveling, or hunting for the best matcha spots.',
        dspPositions: 'Philanthropy Chair (Fall 2025)',
        committees: 'Standards, Philanthropy (Fall 2025)',
        careerInterests: 'Human Resources, Audit',
        pastRoles: 'Philanthropy Chair at Delta Sigma Pi (May 2025 - Present), Human Resources Manager at Fourier Fund (Mar 2025 - Present), Operations & Talent Management Intern at SBU Career Center (Aug 2024 - May 2025), Student Engagement Specialist at Ion Philanthropy (Oct 2025 - Present), Undergraduate Teaching Assistant at Stony Brook University (Aug 2025 - Present)',
        linkedin: 'https://www.linkedin.com/in/ana-jiang',
        email: 'ana.jiang@stonybrook.edu',
        hobbies: 'Hiking, traveling, taking pictures, and LOVE MATCHA',
        funFact: '',
        personality: '',
        favoriteMemory: '',
        littleQualities: ''
    },
    'Camila Sanchez': {
        image: 'brothers/Camila Sanchez.JPG',
        fullName: 'Camila Sanchez',
        pledgeClass: 'Rho',
        graduationDate: 'May 2028',
        major: 'Business Mgmt (Marketing)',
        bio: 'Hey, I\'m Camila! I handle social media and recruitment for DSP, and I love the creative side of marketing—designing posts and telling brand stories. When I\'m not creating content, I\'m probably listening to Lana del Rey, reading, or working on coloring books. Fair warning: I\'m absolutely terrified of bugs.',
        dspPositions: 'Social Media Chair (Fall 2025), Recruitment Chair (Spring 2026)',
        committees: 'CS/ Philanthropy (Fall 2025), AR/ Philanthropy (Spring 2026)',
        careerInterests: 'Marketing, Public Relations',
        pastRoles: 'Social Media Chair at Delta Sigma Pi (May 2025 - Present), Residential Ambassador at Stony Brook University (Jun 2025 - Jul 2025), Project and Event Coordinator Intern at SBU, Childcare Worker at Marks JCH of Bensonhurst (Sep 2022 - Jun 2024)',
        linkedin: 'https://www.linkedin.com/in/camila6',
        email: 'camila.sanchezsantamaria@stonybrook.edu',
        hobbies: 'Music, Coloring books, Reading, Dance',
        funFact: 'I love dying my hair and I\'m a huge fan of Lana del Rey and The Neighbourhood',
        personality: 'Bright, SMILE, Hardworking',
        favoriteMemory: 'Going out to any social event with my friends in DSP',
        littleQualities: ''
    },
    'Chanul Dandeniya': {
        image: 'brothers/Chanul Dandeniya.jpeg',
        fullName: 'Chanul Dandeniya',
        pledgeClass: 'Rho',
        graduationDate: 'May 2027',
        major: 'Computer Science & Applied Math/Statistics',
        bio: 'What\'s up, I\'m Chanul. I aspire to work in big tech or at a startup one day, somewhere on the software/product side. I\'ve gotten a bit of exposure to both worlds already, and it made me realize how much I enjoy environments where you move fast, learn a ton, and work with good people. Outside of school, I\'m into the gym, basketball, traveling, running, and investing, and I\'m usually either hanging with friends or just taking it easy.',
        dspPositions: '',
        committees: '',
        careerInterests: 'Software Engineering • Product Development • Startups',
        pastRoles: 'Junior Developer at Amazon (Oct 2021 - Oct 2024), Machine Learning Intern at Saiera, Lead Solutions Architect at OuterLabs Studio (Aug 2022 - Jun 2025)',
        linkedin: 'https://www.linkedin.com/in/cdandeniya/',
        email: 'chanul.dandeniya@stonybrook.edu',
        hobbies: 'Gym, basketball, traveling, running, investing, spontaneity',
        funFact: 'I made the Brother Directory!',
        personality: 'nonchalant',
        favoriteMemory: 'Skydiving with my big, chilling with the brothers after chapter.',
        littleQualities: ''
    },
    'Sandra Obrycki': {
        image: 'brothers/Sandra Obrycki.png',
        fullName: 'Sandra Obrycki',
        pledgeClass: 'Nu',
        graduationDate: 'May 2026',
        major: 'Business Mgmt (Marketing & Finance)',
        bio: 'Hi, I\'m Sandra! I love fashion and brand marketing—it\'s the perfect mix of business strategy and creative storytelling. Currently serving as VPPA, I\'ve held various leadership roles in DSP including Social Chair and PE. I\'ve done marketing internships at Eagle Rock Properties and SBU, and I studied abroad in Italy which was amazing. When I\'m not working on campaigns or planning events, I\'m usually baking, doing pilates, reading, shopping, or hiking.',
        dspPositions: 'Social Chair (Spring 2024), PE (Spring 2025), VPPA (25-26)',
        committees: 'Professional Development, Philanthropy (Fall 2024 - Fall 2025)',
        careerInterests: 'Fashion/Brand Marketing',
        pastRoles: 'Marketing Intern at Eagle Rock Properties (Summer 2025 - Present), Marketing Intern at SBU Budget & Financial Planning & Analysis',
        linkedin: 'http://linkedin.com/in/sandra-obrycki',
        email: 'sandra.obrycki@stonybrook.edu',
        hobbies: 'Baking, Pilates, Reading, Shopping, Hiking',
        funFact: 'Studied abroad in Italy for a summer',
        personality: 'Bubbly, compassionate, kind',
        favoriteMemory: 'Going to dinners with my littles!!',
        littleQualities: ''
    },
    'Vincent Ouyang': {
        image: 'brothers/Vincent Ouyang.jpg',
        fullName: 'Vincent Ouyang',
        pledgeClass: 'Nu',
        graduationDate: 'May 2026',
        major: 'Business Mgmt (Finance & Marketing)',
        bio: 'Hey, I\'m Vincent! I\'m into strategy analysis and using data to make better business decisions. I\'ve served as Social Chair and PEA in DSP, and I\'m also the President and Captain of the Volleyball Club here at Stony Brook. I\'ve done internships at Lishawn\'s Consulting and worked on various consulting projects. When I\'m not analyzing data or playing volleyball, I\'m usually bowling, at the gym, or just hanging out with friends.',
        dspPositions: 'Social Chair (Fall 2023), PEA (Spring 2025)',
        committees: 'Philanthropy (Fall 2024), PDC (Fall 2025)',
        careerInterests: 'Strategy Analyst',
        pastRoles: 'Business Intern at Lishawn\'s Consulting (Summer 2024, Summer 2023), Social Event Coordinator at Delta Sigma Pi (Apr 2023 - Apr 2024), President and Captain of Volleyball Club at Stony Brook',
        linkedin: 'https://www.linkedin.com/in/vincent-ouyang-o9/',
        email: 'vincent.ouyang@stonybrook.edu',
        hobbies: 'Volleyball, Bowling, Going to the Gym',
        funFact: 'Eat, sleep, rave',
        personality: 'Crazy, Chill, Paranoid',
        favoriteMemory: 'Formal/Hoco: Hanging with all the goofs',
        littleQualities: ''
    },
    'Michelle Weng': {
        image: 'brothers/Michelle Weng.jpeg',
        fullName: 'Michelle Weng',
        pledgeClass: 'Nu',
        graduationDate: 'May 2026',
        major: 'Business Mgmt (Finance), Minor in Accounting',
        bio: 'Hi, I\'m Michelle! I\'m all about accounting and finance. I\'ve interned at KPMG (twice!), Point72, and NYC Health + Hospitals, and I have an incoming Tax Intern position at KPMG. I\'ve served as Recruitment Chair, PEA, and VPPA in DSP, and I also work as a Peer Career Coach at the SBU Career Center. When I\'m not crunching numbers or helping students, I\'m probably drinking matcha, doing karaoke, baking, or planning my next trip.',
        dspPositions: 'Recruitment Chair (Fall 2023), PEA (Spring 2024), VPPA (24-25)',
        committees: 'Philanthropy (Spring 2025)',
        careerInterests: 'Accounting and Finance',
        pastRoles: 'Incoming Tax Intern at KPMG US (Aug 2025 - Present), Regulatory Reporting Intern at Point72 (Jun 2025 - Aug 2025), Data Analyst Intern at Stony Brook University Career Center (Aug 2024 - May 2025), Senior Peer Career Coach Intern at SBU Career Center (May 2024 - May 2025), Peer Career Coach Intern at SBU Career Center (Aug 2023 - May 2024), Embark Scholar Intern at KPMG US (Jun 2024 - Aug 2024), Winter Finance Intern at NYC Health + Hospitals (Dec 2023 - Jan 2024)',
        linkedin: 'https://www.linkedin.com/in/-michelle-weng',
        email: 'Michelle.weng.1@stonybrook.Edu',
        hobbies: 'Matcha, karaoke, baking, travel',
        funFact: '',
        personality: '',
        favoriteMemory: '',
        littleQualities: ''
    },
    'Daniel Yoo': {
        image: 'brothers/Daniel Yoo.jpeg',
        fullName: 'Daniel Yoo',
        pledgeClass: 'Nu',
        graduationDate: 'May 2026',
        major: 'Applied Math/Statistics & Economics',
        bio: 'Hey, I\'m Daniel! I love using data and quantitative analysis to solve financial problems. I\'ve served as VP Scholarships & Awards, Social Chair, and PE in DSP. Currently interning at Wells Fargo in Consumer Lending, I\'ve also worked at World Insurance Associates and the SBU Career Center. When I\'m not analyzing data or building financial models, I\'m probably playing volleyball.',
        dspPositions: 'VP Scholarships & Awards (23-24), Social Chair (Spring 2025), PE (Fall 2025)',
        committees: 'Professional Development, Philanthropy',
        careerInterests: 'Quantitative Finance, Financial Analytics',
        pastRoles: 'Consumer Lending Intern at Wells Fargo (Jun 2025 - Present), Risk Management Intern at World Insurance Associates LLC (May 2024 - May 2025), Operations and Talent Management Intern at SBU Career Center (Aug 2023 - May 2024), Financial Planning Analyst Intern at Delta Galil Industries (Apr 2023 - Aug 2023)',
        linkedin: 'https://www.linkedin.com/in/daniel-yoo-/',
        email: 'daniel.yoo@stomybrook.edu',
        hobbies: 'Volleyball',
        funFact: '',
        personality: '',
        favoriteMemory: '',
        littleQualities: ''
    },
    'Rainer Duchmanh': {
        image: 'brothers/Rainer Duchmanh.jpeg',
        fullName: 'Rainer Duchmanh',
        pledgeClass: 'Xi',
        graduationDate: 'May 2026',
        major: 'Business Admin & Mgmt (Finance & Economics)',
        bio: 'Hey, I\'m Rainer! I\'m into wealth management and financial analysis. I\'ve been interning at Snyder Wealth Group and worked as a Junior Analyst at Fourier Fund. I\'ve also coached sports and worked as a summer camp counselor, which taught me a lot about leadership. When I\'m not working on financial planning, I\'m probably playing soccer.',
        dspPositions: 'Alumni Relations Chair (Fall 2024)',
        committees: 'Alumni Committee',
        careerInterests: '',
        pastRoles: 'Wealth Management Intern at Snyder Wealth Group (May 2024 - Present), Junior Analyst at Fourier Fund (Feb 2025 - Aug 2025), Sports Coach at F.A.S.T. Athletics (Sep 2023 - May 2024), Head Summer Camp Counselor at Elmsford Day Camp (Jun 2023 - Aug 2023)',
        linkedin: 'https://www.linkedin.com/in/rainer-ducmanh/',
        email: 'rainer.ducmanh@stonybrook.edu',
        hobbies: 'Soccer',
        funFact: '',
        personality: '',
        favoriteMemory: '',
        littleQualities: ''
    },
    'Karan Grover': {
        image: 'brothers/Karan Grover.JPG',
        fullName: 'Karan Grover',
        pledgeClass: 'Xi',
        graduationDate: 'May 2026',
        major: 'Applied Math/Statistics & Economics',
        bio: 'Hey, I\'m Karan! I\'m into data analytics, consulting, and HR analytics. Currently serving as President of Delta Sigma Pi, I\'ve held various leadership roles including VPAR and Alumni Relations Chair. I\'ve interned at PSEG in People Analytics and worked as a Peer Career Coach at the SBU Career Center. When I\'m not analyzing data or leading the chapter, I\'m watching F1 or basketball, listening to music, or watching movies.',
        dspPositions: 'Alumni Relations Chair (Spring 2024), VPAR (24-25), President (25-26)',
        committees: 'Alumni Relations (Spring 2024)',
        careerInterests: 'Data Analytics, Consulting, and HR Analytics',
        pastRoles: 'President at Delta Sigma Pi (Apr 2025 - Present), Vice President of Alumni Relations at Delta Sigma Pi (Apr 2024 - Apr 2025), People Analytics Intern at PSEG (Jun 2025 - Dec 2025), Peer Career Coach at SBU Career Center (Aug 2024 - May 2025), Data Entry Intern at International Rescue Committee (Jun 2024 - Aug 2024), Summer Housing Assistant at SBU (May 2024 - Aug 2024)',
        linkedin: 'https://www.linkedin.com/in/karan-grover-2005kg/',
        email: 'karan.grover@stonybrook.edu',
        hobbies: 'Watching Sports (F1 and Basketball), Listening to music, Watching movies',
        funFact: 'I skipped a grade',
        personality: 'Inquisitive',
        favoriteMemory: 'Picking up all my littos',
        littleQualities: ''
    },
    'Adrian Morel': {
        image: 'brothers/Adrian Morel.jpeg',
        fullName: 'Adrian Morel',
        pledgeClass: 'Xi',
        graduationDate: 'May 2026',
        major: 'Business Mgmt, Minor in Applied Math/Statistics',
        bio: 'Hey, I\'m Adrian! I\'m into asset management and financial analysis. I interned at JPMorgan Chase and have served as Senior Vice President and Recruitment Chair in DSP. I also work part-time at Target and Starbucks to balance everything. When I\'m not analyzing portfolios or managing recruitment, I\'m usually working or hanging out with brothers.',
        dspPositions: 'Recruitment Chair (Fall 2023), SVP (24-25)',
        committees: 'Philanthropy (Spring 2026)',
        careerInterests: '',
        pastRoles: 'Asset Management Summer Analyst at JPMorgan Chase (Jun 2024 - Aug 2025), Senior Vice President at Delta Sigma Pi (Apr 2024 - Apr 2025), Recruitment Chair at Delta Sigma Pi (Dec 2023 - May 2024), Customer Service Advocate/Fulfillment Expert at Target (Oct 2021 - Present), Barista at Starbucks (Aug 2022 - Present)',
        linkedin: 'https://www.linkedin.com/in/adrian-morel1/',
        email: 'adrian.morel@stonybrook.edu',
        hobbies: '',
        funFact: '',
        personality: '',
        favoriteMemory: '',
        littleQualities: ''
    },
    'Laaibah Shoaib': {
        image: 'brothers/Laaibah Shoaib.JPG',
        fullName: 'Laaibah Shoaib',
        pledgeClass: 'Xi',
        graduationDate: 'May 2026',
        major: 'Technological Systems Management (Information Systems), Minor in Film & Screen Studies',
        bio: 'Hi, I\'m Laaibah! I love project management, business analytics, and the media/entertainment industry. Currently serving as Recruitment Chair in DSP, I\'ve worked as a Budget Intern at SBU, Writing Tutor, and Peer Mentor for CEAS. I\'ve done various project management internships and I\'m part of the Emma Bowen Foundation program. When I\'m not managing projects or analyzing data, I\'m reading, making playlists, shopping, or watching movies.',
        dspPositions: 'Recruitment Chair',
        committees: 'CS, Academic Success',
        careerInterests: 'Technical Project Management, Business Analytics, Media and Entertainment',
        pastRoles: 'Budget, Financial Planning, and Analysis Intern at SBU (Jun 2025 - Present), Writing Tutor at SBU (Feb 2024 - Aug 2025), Media Research Intern at TVB (Aug 2025 - Dec 2025), Project Management Team Lead at JBIER Inc. (May 2025 - Jul 2025), Project Management Intern at JBIER Inc. (Feb 2025 - Jul 2025), Business Development Intern at Remotely Good (Jul 2025 - Aug 2025), Launch Career Activation Program Participant at Emma Bowen Foundation (Jan 2026 - Present), Peer Mentor for CEAS',
        linkedin: 'https://www.linkedin.com/in/laaibah-shoaib',
        email: 'laaibah.shoaib@stonybrook.edu',
        hobbies: 'Reading, listening to music + making playlists, fashion, shopping, watching movies',
        funFact: 'I played violin for 8 years',
        personality: '',
        favoriteMemory: '',
        littleQualities: ''
    },
    'Brian Ren': {
        image: 'brothers/Brian Ren.png',
        fullName: 'Brian Ren',
        pledgeClass: 'Omicron',
        graduationDate: 'May 2026',
        major: 'Business, ACC+ISE minor',
        bio: 'Hey, I\'m Brian! I\'m focused on accounting and audit. I\'ve done the KPMG Embark Scholar program and have an incoming Audit Intern position there. I\'ve also worked as a Tax Intern and volunteered with VITA doing tax prep. I served as Philanthropy Chair in DSP and I love teaching and working with students.',
        dspPositions: 'Philanthropy Chair',
        committees: 'Professional Development, Community Service, Philanthropy, Academic Success, Alumni Relations, Standards',
        careerInterests: 'Auditing',
        pastRoles: 'Embark Intern @ KPMG',
        linkedin: 'linkedin.com/in/brian-ren',
        email: 'brian.ren@stonybrook.edu',
        hobbies: 'Hanging out with friends, going to the gym, playing guitar',
        funFact: 'I caught a baby shark once while fishing',
        personality: '',
        favoriteMemory: 'When Jack Hardiman and I fought 2 guys behind the library',
        littleQualities: ''
    },
    'Estella Saha': {
        image: 'brothers/Estella Saha.jpeg',
        fullName: 'Estella Saha',
        pledgeClass: 'Omicron',
        graduationDate: 'May 2026',
        major: 'Applied Math/Statistics, Minor in Philosophy',
        bio: 'Hey, I\'m Estella! I\'m into quant finance, data science, and research. I\'m VP of Film Club and do quant research on campus. I\'ve been involved in various research projects, tutoring, and clubs. I served as Marketing Chair in DSP. When I\'m not researching or studying, I\'m into art, anime, film, video games, music, photography, fashion, chess, philosophy, and reading.',
        dspPositions: 'Marketing Chair (Fall 2024)',
        committees: 'Philanthropy (Spring 2025)',
        careerInterests: 'Quant Finance, Data Science',
        pastRoles: 'Vice President at Film Club (Jan 2024 - Present), Undergraduate Quant Finance Researcher at SBU (Aug 2023 - Present), Research Assistant at Vertically Integrated Projects - Automotive Ethics Team (Sep 2024 - May 2025), Linear Algebra Tutor at ASTC (Aug 2023 - May 2025), Research Assistant at Mckinnon Rosati Lab (Sep 2024 - Jan 2025)',
        linkedin: 'https://www.linkedin.com/in/estellasaha',
        email: 'estella.saha@stonybrook.edu',
        hobbies: 'Art, anime/manga/manhwa, film, video games, music, photography, fashion, chess, philosophy, reading',
        funFact: 'I\'ve been told I look like Jenna Ortega well over 50 times',
        personality: 'Lowkey a narcissist',
        favoriteMemory: 'Making tiramisu',
        littleQualities: ''
    },
    'Naoki Sekine': {
        image: 'brothers/Naoki Sekine.jpeg',
        fullName: 'Naoki Sekine',
        pledgeClass: 'Omicron',
        graduationDate: 'May 2026',
        major: 'Business Mgmt (Marketing) & Economics',
        bio: 'Hi, I\'m Naoki! I currently serve as Vice President of Alumni Relations for Delta Sigma Pi and work as a Senior Marketing Intern at the Stony Brook University Career Center. My career interests include marketing analytics, advertising, and entrepreneurship. I\'m also a member of the Japanese Student Organization, where I previously served as Vice President. In addition, I\'m a content creator with 900K+ followers on TikTok (@naoki_sekine). My favorite artist is Japanese pop singer Yuuri.',
        dspPositions: 'Webmaster (Fall 2024), VPAR (25-26)',
        committees: 'Philanthropy (Spring 2025), PDC, AR',
        careerInterests: 'Marketing Analysis, Advertising',
        pastRoles: 'Senior Marketing Intern at SBU Career Center (May 2025 - Present), Marketing Intern at SBU Career Center (Aug 2024 - May 2025), Vice President of Alumni Relations at Delta Sigma Pi (Apr 2025 - Present), Webmaster Chair at Delta Sigma Pi (May 2024 - Dec 2024), Vice President at Japanese Student Organization (May 2024 - May 2025), Digital Strategy & Activation Intern at Publicis Groupe, Content Creator on TikTok (@naoki_sekine) (Mar 2019 - Present), Content Creator on Instagram (@naoki_sekine) (Sep 2022 - Present)',
        linkedin: 'https://www.linkedin.com/in/naoki-sekine',
        email: 'Naoki.sekine@stonybrook.edu',
        hobbies: 'Speed Stacking, walks, hanging out with friends, Japanese culture/music',
        funFact: 'I\'m 12% Korean',
        personality: 'Fast-paced, energetic, reliable',
        favoriteMemory: 'Attending LEAD conference for the first time',
        littleQualities: ''
    },
    'Carrie Song': {
        image: 'brothers/Carrie Song.JPG',
        fullName: 'Carrie Song',
        pledgeClass: 'Omicron',
        graduationDate: 'Fall 2026',
        major: 'Business Mgmt (Marketing & Operations), Minor in Communication',
        bio: 'Hi, I\'m Carrie! I\'m all about HR and currently serving as SVP in DSP. I\'ve served as Social Media Chair and DEI Chair, and I\'ve interned at NYC Health and Hospitals Bellevue and Rudin in HR. I also work as an Office Assistant at SBU Campus Residences. When I\'m not working on HR stuff or managing social media, I\'m reading, shopping, traveling, trying new foods, or going to concerts.',
        dspPositions: 'Social Media Chair (Fall 2024), DEI Chair (Spring 2025), SVP (25-26)',
        committees: 'Professional Development (Spring 2025)',
        careerInterests: 'HR',
        pastRoles: 'Senior Vice President at Delta Sigma Pi (May 2025 - Present), DEI Chair at Delta Sigma Pi (Dec 2024 - May 2025), Social Media Chair at Delta Sigma Pi (May 2024 - Jan 2025), Human Resources Intern at Rudin (Jun 2025 - Aug 2025), Human Resources Intern at NYC Health+Hospitals Bellevue (May 2024 - Aug 2024), Campus Residences Office Assistant at SBU (Jan 2025 - Present), Orientation Leader at SBU (Jan 2024 - Jul 2025), DEI Chair at Women In Business (Aug 2024 - May 2025)',
        linkedin: 'https://www.linkedin.com/in/carrie-song-',
        email: 'carrie.song@stonybrook.edu',
        hobbies: 'Reading, shopping, traveling, and trying new foods, going to concerts',
        funFact: 'I\'ve been to 6 countries',
        personality: '',
        favoriteMemory: 'Secret Santa',
        littleQualities: ''
    },
    'Madison Stone': {
        image: 'brothers/Madison Stone.jpg',
        fullName: 'Madison Stone',
        pledgeClass: 'Omicron',
        graduationDate: 'May 2026',
        major: 'Business Mgmt (Finance & Operations Mgmt), Minor in Theatre Arts',
        bio: 'Hey, I\'m Madison! I\'m into the business side of the entertainment industry. I served as Recruitment Chair in DSP and I work in the restaurant industry. I also did an internship at The Fashion Foundation. When I\'m not working or studying, I\'m dancing, doing pilates, listening to music, or reading about astrology.',
        dspPositions: 'Recruitment Chair (Fall 2024)',
        committees: 'CS, Professional Development (Fall 2025)',
        careerInterests: 'Business side of the entertainment industry',
        pastRoles: 'E-Commerce Intern at The Fashion Foundation (Jan 2025 - Aug 2025), Recruitment Chair at Delta Sigma Pi (Apr 2024 - Dec 2024), Waitress at Big Daddy\'s Restaurant (Aug 2023 - Present), Hostess at Big Daddy\'s Restaurant (Jul 2021 - Aug 2023)',
        linkedin: 'https://www.linkedin.com/in/madison-stone1/',
        email: 'Madison.stone@stonybrook.edu',
        hobbies: 'Dancing, pilates, music, astrology',
        funFact: 'I have a dog named Diggity',
        personality: 'Caring, friendly, creative',
        favoriteMemory: 'Seeing how much all of the brothers want to help each other and genuinely want the best for each other',
        littleQualities: ''
    },
    'Isabelle Baginski': {
        image: 'brothers/Isabelle Baginski.jpg',
        fullName: 'Isabelle Baginski',
        pledgeClass: 'Pi',
        graduationDate: 'May 2026',
        major: 'Applied Math/Statistics & Business Mgmt (Accounting)',
        bio: 'Hey, I\'m Isabelle! I\'m focused on auditing and getting my CPA. I interned at Deloitte and have a full-time position there starting Fall 2026. I\'ve also worked as a Regulatory Compliance Intern at Teachers Federal Credit Union and serve as VP Scholarships & Awards in DSP. I\'ve been coaching tennis for years. When I\'m not auditing or studying, I\'m playing tennis, hiking, traveling, playing pickleball, or at the beach.',
        dspPositions: 'Recruitment Chair (Spring 2025), VP Scholarships & Awards (25-26)',
        committees: 'CS (Spring 2025)',
        careerInterests: 'Auditing / CPA',
        pastRoles: 'Audit and Assurance Intern at Deloitte (Jun 2025 - Jul 2025), Full-time Audit position at Deloitte (Starting Fall 2026), Regulatory Compliance Intern at Teachers Federal Credit Union (Jun 2024 - Aug 2024), Tennis Coach at Eastern Athletic Club (Jul 2020 - Present)',
        linkedin: 'https://www.linkedin.com/in/isabellebaginski',
        email: 'Isabelle.Baginski@stonybrook.edu',
        hobbies: 'Tennis, Hiking, Traveling, Pickleball, Going to the Beach',
        funFact: 'I have scoliosis',
        personality: 'Adventurous, Outgoing, Hardworking',
        favoriteMemory: 'Took a trip to Puerto Rico with some brothers for Spring Break.',
        littleQualities: ''
    },
    'Jaelyn Gunter': {
        image: 'brothers/Jaelyn Gunter.jpeg',
        fullName: 'Jaelyn Gunter',
        pledgeClass: 'Pi',
        graduationDate: 'May 2026',
        major: 'Business Mgmt (Marketing)',
        bio: 'Hey, I\'m Jaelyn! I love social media marketing, especially in the beauty or sports industry. Currently serving as VPCS in DSP, I\'ve also served as Social Media Chair. I work at Ulta and had a Marketing internship at The Accredited Group. I also work with College Fashionista, collaborating with brands like Prada and Valentino, and I\'ve attended New York Fashion Week. When I\'m not creating content, I love to travel, watch movies, and try new things!',
        dspPositions: 'Social Media Chair (Spring 2025), VPCS (25-26)',
        committees: 'CS',
        careerInterests: 'Social media marketing in beauty or sports industry',
        pastRoles: 'Vice President of Community Service at Delta Sigma Pi (May 2025 - Present), Social Media Chair at Delta Sigma Pi (Dec 2024 - May 2025), Marketing Intern at The Accredited Group (Jun 2025 - Aug 2025), Beauty Advisor at Ulta Beauty (Aug 2024 - Present), College Fashionista (Jan 2023 - Present), Children\'s Party Host at All Sportz Melville (Nov 2024 - Present)',
        linkedin: 'https://www.linkedin.com/in/jaelyn-gunter-9b5935263',
        email: 'jaelyn.gunter@stonybrook.edu',
        hobbies: 'I love to travel, watch movies & try new things!',
        funFact: 'I\'ve been to Puerto Rico more than 10 times',
        personality: 'Passionate, caring & loyal',
        favoriteMemory: 'The day I became a brother ☺️',
        littleQualities: ''
    },
    'Jack Hardiman': {
        image: 'brothers/Jack Hardiman.png',
        fullName: 'Jack Hardiman',
        pledgeClass: 'Pi',
        graduationDate: 'May 2026',
        major: 'Economics & Atmospheric Science',
        bio: 'Hey, I\'m Jack! I\'m interested in energy trading and I work as a weather forecaster. I interned at the Town of Oyster Bay in Emergency Management & Public Safety. When I\'m not forecasting weather or studying economics, I\'m hiking, cooking, or boxing.',
        dspPositions: 'n/a',
        committees: 'CS',
        careerInterests: 'Energy Trader',
        pastRoles: 'Emergency Management & Public Safety Intern at Town of Oyster Bay (May 2025 - Aug 2025), Weather forecaster',
        linkedin: 'https://www.linkedin.com/in/jackhardiman54',
        email: 'jack.hardiman@stonybrook.edu',
        hobbies: 'Hiking, cooking, boxing',
        funFact: 'I\'ve been to Africa',
        personality: 'Easygoing, nice, good',
        favoriteMemory: 'When Brian Ren and I took on those 2 guys behind the library',
        littleQualities: ''
    },
    'Rashna Kasaju': {
        image: 'brothers/Rashna Kasaju.jpeg',
        fullName: 'Rashna Kasaju',
        pledgeClass: 'Pi',
        graduationDate: 'May 2027',
        major: 'Business Mgmt (Marketing) & Environmental Design, Policy, and Planning',
        bio: 'Hey, I\'m Rashna! I\'m into digital marketing and teaching. Currently serving as PEA in DSP, I\'ve also served as Marketing Chair. I\'ve been working with social media since I was 11 and I\'m a Social Media Creator and Ambassador on Instagram. I\'ve done various marketing internships and special education roles. When I\'m not creating content or teaching, I\'m playing guitar, singing, cooking, baking, playing video games, or doing pilates.',
        dspPositions: 'Marketing Chair (Spring 2025), PEA (Fall 2025)',
        committees: 'Standards (Fall 2025)',
        careerInterests: 'Digital Marketing, Marketing, Teaching',
        pastRoles: 'Social Media Creator and Ambassador on Instagram (Apr 2017 - Present), Public Relations Officer at Women In Business (May 2025 - Present), Undergraduate Teaching Assistant at SBU (Aug 2025 - Dec 2025), Social Media and Marketing at SBU (Aug 2025 - Jan 2026), Undergraduate Research Team Leader at Blockchain Business Lab (Jan 2025 - Sep 2025), Special Education Aide at Bethpage Union Free School (Jul 2025 - Aug 2025)',
        linkedin: 'https://www.linkedin.com/in/rashna-kasaju',
        email: 'rashna.kasaju@stonybrook.edu',
        hobbies: 'Guitar, singing, cooking, baking, video games, Pilates and fitness',
        funFact: 'I\'ve been working with social media since I was 11!',
        personality: 'Open-minded, ambitious, and creative',
        favoriteMemory: 'Beach cleanups!',
        littleQualities: ''
    },
    'Yuta Kawamura': {
        image: 'brothers/Yuta Kawamura.jpeg',
        fullName: 'Yuta Kawamura',
        pledgeClass: 'Pi',
        graduationDate: 'May 2026',
        major: 'Economics',
        bio: 'Hey, I\'m Yuta! I\'m into finance and I interned at Treasure Data in Marketing. I\'ve served as Alumni Relations Chair in DSP and have experience as a Resident Assistant and Microeconomics Teacher Assistant. I was also President of the International Student Association at Purchase College. When I\'m not working or studying, I\'m playing football (soccer), playing poker, or traveling.',
        dspPositions: 'Alumni Relations Chair (Spring 2025)',
        committees: 'AR (Spring 2025)',
        careerInterests: 'Finance',
        pastRoles: 'Marketing Intern at Treasure Data (Jun 2025 - Sep 2025), Resident Assistant at SUNY Purchase College (Aug 2023 - May 2024), Microeconomics Teacher Assistant at SUNY Purchase College (Jan 2023 - May 2024), President of International Student Association at SUNY Purchase College (Aug 2022 - May 2024)',
        linkedin: 'https://www.linkedin.com/in/yutak11',
        email: 'yuta.kawamura@stonybrook.edu',
        hobbies: 'Football (not the American one, the true football), poker, Traveling',
        funFact: 'Been to 37 countries',
        personality: '',
        favoriteMemory: '',
        littleQualities: ''
    },
    'Connor Wong': {
        image: 'brothers/Connor Wong.jpeg',
        fullName: 'Connor Wong',
        pledgeClass: 'Pi',
        graduationDate: 'May 2027',
        major: 'Business Mgmt (Marketing & Finance)',
        bio: 'Hey, I\'m Connor! I\'m interested in marketing, finance analytics, or administrative roles—maybe insurance too. Currently serving as Chancellor in DSP, I\'ve interned for the EMS FDNY fundraiser and at David Louie insurance company. I\'m also doing an externship at Canon USA. When I\'m not working or studying, I\'m into music, fashion, bouldering, biking, eating, and traveling.',
        dspPositions: 'Chancellor (25-26)',
        committees: 'Professional Development (Spring 2025)',
        careerInterests: 'Marketing, Finance Analytics, Administrative roles, Insurance',
        pastRoles: 'Chancellor at Delta Sigma Pi (May 2025 - Present), Developing Professionals Leveraging Networks Externship at Canon USA (Aug 2025 - Present), Administrative Assistant Intern for EMS FDNY fundraiser, Intern at David Louie insurance company, Summer Intern at EMS FDNY Help Fund (May 2024 - Jul 2024)',
        linkedin: 'https://www.linkedin.com/in/connor-wong1',
        email: 'connor.wong@stonybrook.edu',
        hobbies: 'Music, fashion, bouldering, biking, eating, traveling',
        funFact: 'Traveled four countries in one month!',
        personality: '',
        favoriteMemory: '',
        littleQualities: ''
    },
    'Samuel Zou': {
        image: 'brothers/Samuel Zou.jpeg',
        fullName: 'Samuel Zou',
        pledgeClass: 'Pi',
        graduationDate: 'May 2027',
        major: 'Applied Math/Statistics & Economics',
        bio: 'Hey, I\'m Samuel! I\'m into actuarial work, data analytics, and financial analytics. Currently serving as VPF in DSP, I\'ve also served as Philanthropy Chair. I work as an Administrative Assistant at a non-profit (AWCWA) and do data & financial analytics research. When I\'m not analyzing data or building financial models, I\'m cooking, doing arts & crafts, going to concerts, playing billiards, or listening to music.',
        dspPositions: 'Philanthropy Chair (Spring 2025), VPF (25-26)',
        committees: 'AR/Professional Development, Philanthropy (Spring 2025)',
        careerInterests: 'Actuary, Data Analytics, Financial Analytics',
        pastRoles: 'Vice President of Finance at Delta Sigma Pi (May 2025 - Present), Philanthropy Chairperson at Delta Sigma Pi (Dec 2024 - May 2025), Administrative Assistant at AWCWA (Jul 2024 - Aug 2024), Data & Financial Analytics Researcher',
        linkedin: 'https://www.linkedin.com/in/samuel-zou',
        email: 'samuel.zou@stonybrook.edu',
        hobbies: 'Cooking, Arts & Crafts, Concerts, Billiards, and Music',
        funFact: 'I\'m allergic to peanuts but I love eating peanut butter noodles.',
        personality: 'Chill, Hardworking, Funny',
        favoriteMemory: 'Semi-Formal',
        littleQualities: ''
    },
    'Steven Ye': {
        image: 'brothers/Steven Ye.jpeg',
        fullName: 'Steven Ye',
        pledgeClass: 'Rho',
        graduationDate: 'May 2027',
        major: 'Applied Math/Statistics & Economics',
        bio: 'Hey, I\'m Steven! I\'m into finance and currently serve as Alumni Chair in DSP. I work as an Audio Visual Technician at SBU and I\'ve managed the Residential Fitness Center. When I\'m not working or studying, I\'m hanging out with friends or sleeping.',
        dspPositions: 'Alumni Chair (Fall 2025)',
        committees: 'Professional Development/AR (Fall 2025)',
        careerInterests: 'Finance',
        pastRoles: 'Alumni Chair at Delta Sigma Pi (Aug 2025 - Present), Audio Visual Technician at SBU (Oct 2025 - Present), Residential Fitness Center Manager at SBU (Oct 2024 - Jun 2025), Warehouse Staff at SBU (Apr 2024 - Sep 2024)',
        linkedin: 'https://www.linkedin.com/in/steven-ye7/',
        email: 'steven.ye@stonybrook.edu',
        hobbies: 'Hanging out with friends and sleeping',
        funFact: 'Aldo\'s my twin',
        personality: 'Cool',
        favoriteMemory: 'Semi-Formal',
        littleQualities: ''
    },
    'Charleen You': {
        image: 'brothers/Charleen You.jpeg',
        fullName: 'Charleen You',
        pledgeClass: 'Rho',
        graduationDate: 'May 2027',
        major: 'Business Mgmt (Operations & Marketing)',
        bio: 'Hey, I\'m Charleen! I\'m into HR or Marketing and currently serve as VPCO in DSP. I\'ve interned in HR at Paybility Financial and work as a Student Tech at DoIT. When I\'m not working or studying, I\'m traveling, hopping around matcha cafes, or watching movies.',
        dspPositions: 'VPCO (25-26)',
        committees: 'n/a',
        careerInterests: 'HR or Marketing',
        pastRoles: 'VPCO (Secretary) at Delta Sigma Pi (May 2025 - Present), Human Resources Intern at Paybility Financial (Jan 2025 - Apr 2025), Client Support Student Technician at SBU (May 2024 - Present), Student Technician at SBU (Jan 2024 - May 2024)',
        linkedin: 'https://www.linkedin.com/in/charleen-you/',
        email: 'charleen.you@stonybrook.edu',
        hobbies: 'Traveling, Matcha cafe hopping, and watching movies',
        funFact: '',
        personality: 'Bubbly, curious, and optimistic',
        favoriteMemory: 'Taking the same classes with brothers and being able to work on group projects',
        littleQualities: ''
    },
    'Hannah Kim': {
        image: 'brothers/Hannah Kim.jpeg',
        fullName: 'Hannah Kim',
        pledgeClass: 'Rho',
        graduationDate: 'May 2027',
        major: 'Business Mgmt (Finance)',
        bio: 'Hey, I\'m Hannah! I\'m into Human Resources and currently serve as Marketing Chair in DSP. I\'m interning at The Peninsula New York in HR. When I\'m not working or studying, I\'m shopping, going to concerts, or exploring the city.',
        dspPositions: 'Marketing Chair (Fall 2025)',
        committees: 'n/a',
        careerInterests: 'Human Resources',
        pastRoles: 'People and Culture Intern at The Peninsula Hotels (Jun 2025 - Present)',
        linkedin: 'https://www.linkedin.com/in/hannah-kim5275',
        email: 'hannah.h.kim@stonybrook.edu',
        hobbies: 'Shopping, attending concerts, and going out in the city',
        funFact: 'I eat spicy wontons three times a week',
        personality: 'Outgoing, sociable, friendly',
        favoriteMemory: 'Formal last Spring of 2025 after I crossed. I had such a fun time with my class and brothers overall.',
        littleQualities: ''
    },
    'Anna Lin': {
        image: 'brothers/Anna Lin.JPG',
        fullName: 'Anna Lin',
        pledgeClass: 'Rho',
        graduationDate: 'May 2027',
        major: 'Business Mgmt (Marketing & Operations Mgmt), Minor in Real Estate & Insurance',
        bio: 'Hey, I\'m Anna! I\'m into Product Management, Product Marketing, and Operations Analyst roles. Currently serving as Alumni Relations Chair in DSP, I work as a Student Technician at DoIT and I\'m Public Relations Director & Fundraising Chair at Fujianese Culture Club. I\'m also a Scholars Mentor. When I\'m not working or studying, I\'m playing sports (soccer, pickleball, volleyball), listening to music, or hanging out with friends.',
        dspPositions: 'Alumni Relations Chair (Spring 2026)',
        committees: 'AR/Philanthropy (Fall 2025)',
        careerInterests: 'Product Management, Product Marketing, Operations Analyst',
        pastRoles: 'Student Technician at SBU (May 2025 - Present), General Manager at New Mun Yuen Restaurant (Sep 2017 - Present), Public Relations Director at Fujianese Culture Club (Jan 2024 - May 2025), Scholars Mentor at University Scholars College, Summer Intern at Liberty Arts Academy (May 2024 - Jul 2024)',
        linkedin: 'https://www.linkedin.com/in/annalin88',
        email: 'anna.lin.2@stonybrook.edu',
        hobbies: 'Sports (Soccer, Pickleball, Volleyball), listening to music, hanging out with friends',
        funFact: 'I have 5 siblings',
        personality: 'Spontaneous, Funny, Chill',
        favoriteMemory: 'Crossing with my class',
        littleQualities: ''
    },
    'Siena Rahman': {
        image: 'brothers/Siena Rahman.jpeg',
        fullName: 'Siena Rahman',
        pledgeClass: 'Rho',
        graduationDate: 'May 2027',
        major: 'Information Systems (Finance) & Applied Math/Statistics',
        bio: 'Hey, I\'m Siena! I\'m all about data analytics and data science. Currently serving as Webmaster in DSP, I\'m an AI/ML Fellow at Cornell Tech and work as a Resident Assistant at SBU. I have an incoming position in Supply Chain Analytics at Zebra Technologies and I did computational math research at FSU. When I\'m not analyzing data or researching, I\'m thrifting, painting, doing makeup, watching anime, or creating IG Reels and TikTok content.',
        dspPositions: 'Webmaster (Fall 2025)',
        committees: 'Professional Development (Fall 2025)',
        careerInterests: 'Data Analyst/Scientist',
        pastRoles: 'AI/ML Fellow at Break Through Tech (May 2025 - Present), AI Studio Fellow at Nestlé (Aug 2025 - Dec 2025), Incoming Supply Chain Analytics at Zebra Technologies, Undergraduate Research Assistant at FSU Department of Mathematics (May 2025 - Jul 2025), Probability & Statistics Teaching Assistant at SBU (Jan 2025 - May 2025), Resident Assistant at SBU',
        linkedin: 'https://www.linkedin.com/in/sienarahman/',
        email: 'siena.rahman@stonybrook.edu',
        hobbies: 'Thrifting, Painting, Makeup, Anime, IG Reels + TikTok 🥀',
        funFact: 'I have 16 piercings ⛓️‍💥',
        personality: 'Silly, Outgoing, Cheerful',
        favoriteMemory: 'Recruitment',
        littleQualities: ''
    },
    'Waylene Hui': {
        image: 'brothers/Waylene Hui.jpeg',
        fullName: 'Waylene Hui',
        pledgeClass: 'Rho',
        graduationDate: 'May 2027',
        major: 'Applied Math/Statistics',
        bio: 'Hey, I\'m Waylene! I currently serve as DEI Chair in DSP and I\'m involved in Professional Development. I\'ve interned at the International Rescue Committee and have experience as a Policy Intern at Coalition for Asian American Children and Families and Development Intern at Apex for Youth.',
        dspPositions: 'DEI Chair (Fall 2025)',
        committees: 'Professional Development (Fall 2025)',
        careerInterests: '',
        pastRoles: 'Intern at International Rescue Committee (Jun 2025 - Present), Policy Intern at Coalition for Asian American Children and Families (Jul 2023 - Aug 2023), Development Intern at Apex for Youth (Jul 2023 - Aug 2023), Apex for Youth Ambassador (Nov 2021 - Jun 2023)',
        linkedin: 'https://www.linkedin.com/in/waylene-hui/',
        email: 'waylene.hui@stonybrook.edu',
        hobbies: '',
        funFact: '',
        personality: '',
        favoriteMemory: '',
        littleQualities: ''
    },
    'Luke Alexander': {
        image: 'brothers/Luke Alexander.jpeg',
        fullName: 'Luke Alexander',
        pledgeClass: 'Rho',
        graduationDate: 'May 2027',
        major: 'Accounting',
        bio: 'Hey, I\'m Luke! I\'m focused on getting my CPA and I serve in Philanthropy/CS in DSP. I had an internship abroad in Muscat, Oman as a Risk Consultant Intern. When I\'m not studying accounting or working, I\'m playing guitar, piano, volleyball, making beats, or listening to music.',
        dspPositions: 'n/a',
        committees: 'Philanthropy/CS (Fall 2025)',
        careerInterests: 'CPA',
        pastRoles: 'Strategy Consulting Intern at the Performance Factory (Dec 2024 - Apr 2025), Risk Consultant Intern in Muscat, Oman',
        linkedin: 'https://www.linkedin.com/in/luke-alexander123',
        email: 'luke.alexander@stonybrook.edu',
        hobbies: 'I play guitar, piano, vball, make beats, listening to music',
        funFact: 'The producer FNZ who co-produced hits like L$D, first person shooter, what did I miss, donda, and purity actually liked one of my beats on instagram',
        personality: 'Go with the flow',
        favoriteMemory: 'My initiation',
        littleQualities: ''
    },
    'Tolu Bolaji': {
        image: 'brothers/Tolu B.jpeg',
        fullName: 'Tolu Bolaji',
        pledgeClass: 'Rho',
        graduationDate: 'May 2027',
        major: 'Business Mgmt (Accounting & Finance)',
        bio: 'Hey, I\'m Tolu! I\'m into accounting and currently serve as Recruitment Chair and Social Chair in DSP. I work as a Fitness Monitor and Intramural Official at SBU. When I\'m not working or studying, I\'m playing basketball, listening to music, eating, playing video games, or checking out cars.',
        dspPositions: 'Recruitment Chair (Fall 2025), Social Chair (Spring 2026)',
        committees: 'Philanthropy (Fall 2025)',
        careerInterests: 'Accounting',
        pastRoles: 'Fitness Monitor at SBU (Jan 2026 - Present), Intramural Official at SBU (Oct 2025 - Present), Sales Associate at PetSmart (Jul 2025 - Dec 2025)',
        linkedin: 'https://www.linkedin.com/in/feyintoluwa-bolaji',
        email: 'tolu.bolaji@stonybrook.edu',
        hobbies: 'Basketball, Music, Food, Video Games, Art, Cars',
        funFact: 'My Spotify Playlist is 7,000+ songs',
        personality: '',
        favoriteMemory: 'Formal',
        littleQualities: ''
    },
    'Henry Cai': {
        image: 'brothers/Henry Cai.jpeg',
        fullName: 'Henry Cai',
        pledgeClass: 'Rho',
        graduationDate: 'May 2027',
        major: 'Applied Math/Statistics & Economics',
        bio: 'Hey, I\'m Henry! I\'m into actuarial work and data analytics. Currently serving as Social Chair in DSP, I work as a Fitness Monitor at SBU and I\'ve done data analytics research and worked as a Data Management Intern at FDNY. When I\'m not analyzing data or working out, I\'m playing volleyball, billiards, ping pong, handball, going to raves, concerts, or checking out fashion.',
        dspPositions: 'Social Chair (Fall 2025)',
        committees: 'Professional Development/Philanthropy (Fall 2025)',
        careerInterests: 'Actuary/Data Analytics',
        pastRoles: 'Fitness Monitor at SBU (Jan 2025 - Present), Data Management Intern at FDNY, Data Analytics Research, Administrative Assistant at NYC Fire Department (Jun 2022 - Aug 2022)',
        linkedin: 'https://www.linkedin.com/in/henry-cai-/',
        email: 'henry.cai@stonybrook.edu',
        hobbies: 'Volleyball, Billiards, Ping Pong, Handball, Raving, Concerts, Fashion',
        funFact: 'I can eat mala everyday',
        personality: 'Outgoing, compassionate, responsible',
        favoriteMemory: 'Formal',
        littleQualities: ''
    },
    'Alex Chan': {
        image: 'brothers/Aex Chan.jpeg',
        fullName: 'Alex Chan',
        pledgeClass: 'Rho',
        graduationDate: 'May 2027',
        major: 'Applied Math/Statistics & Information Systems, Minor in Finance',
        bio: 'Hey, I\'m Alex! I currently serve as Recruitment Chair in DSP and I\'m involved in Standards. I work as a Student Technician Intern at SBU and I\'ve done a Portfolio Analyst Internship at NYC Department of Housing Preservation & Development.',
        dspPositions: 'Recruitment Chair (Fall 2025)',
        committees: 'Standards (Fall 2025)',
        careerInterests: '',
        pastRoles: 'Student Technician Intern at SBU (Feb 2025 - Present), Portfolio Analyst Intern at NYC Department of Housing Preservation & Development (Jul 2025 - Aug 2025), Warehouse Staff at SBU (Apr 2024 - Feb 2025)',
        linkedin: 'https://www.linkedin.com/in/alex-chan-/',
        email: 'alex.chan@stonybrook.edu',
        hobbies: '',
        funFact: '',
        personality: '',
        favoriteMemory: '',
        littleQualities: ''
    },
    'Walter Benitez': {
        image: 'brothers/Walter.jpeg',
        fullName: 'Walter Benitez',
        pledgeClass: 'Sigma',
        graduationDate: 'May 2028',
        major: 'Economics, Minor in Applied Math/Statistics',
        bio: 'Hey, I\'m Walter! I\'m interested in government and policy work. Currently serving as DEI Chair in DSP, I\'m a research assistant in the Blockchain Business Lab and I do research on textile waste policy. I\'m also involved with The Climate Reality Project. When I\'m not researching or studying, I\'m fishing, hanging by water, or watching Pixar movies (I watch them when I study). I want to learn to skateboard and play guitar.',
        dspPositions: 'DEI Chair (Spring 2026)',
        committees: 'Professional Development',
        careerInterests: 'Government and Policy',
        pastRoles: 'Undergraduate Research Assistant - Blockchain Business Lab at SBU (Aug 2025 - Present), Undergraduate Research Assistant - Textile Waste Policy at SBU (May 2025 - Present), Climate Reality Training Mentor at The Climate Reality Project (Apr 2024 - Jul 2025)',
        linkedin: 'https://www.linkedin.com/in/walter-jacob-benitez-481529332/',
        email: 'benitez.walter@stonybrook.edu',
        hobbies: 'Fishing, hanging by water, watching Pixar movies, want to learn skateboarding and guitar',
        funFact: 'I have 40+ chickens and 4 cats',
        personality: 'Unserious but serious',
        favoriteMemory: 'Anytime we get food',
        littleQualities: ''
    },
    'Jenny Chen': {
        image: 'brothers/Jenny Chen.jpeg',
        fullName: 'Jenny Chen',
        pledgeClass: 'Sigma',
        graduationDate: 'May 2027',
        major: 'Business Mgmt (Operations) & Psychology',
        bio: 'Hey, I\'m Jenny! I\'m into Human Resources and currently serve as Recruitment Chair in DSP. I work as an Administrative & Communications Intern at CAS Dean\'s Office and as a Clinical Operations Student Assistant at the School of Dental Medicine. When I\'m not working or studying, I\'m strength training, collecting jewelry, or listening to music.',
        dspPositions: 'Recruitment Chair (Spring 2026)',
        committees: 'Community Service, Philanthropy (Spring 2026)',
        careerInterests: 'Human Resources',
        pastRoles: 'Recruitment Chair at Delta Sigma Pi (Dec 2025 - Present), Clinical Operations Student Assistant at SBU School of Dental Medicine (Sep 2025 - Present), Administrative and Communications Intern at CAS Dean\'s Office (Oct 2024 - Present)',
        linkedin: 'https://www.linkedin.com/in/jennychen8865',
        email: 'jenny.chen.12@stonybrook.edu',
        hobbies: 'Strength training, collecting jewelry, listening to music',
        funFact: 'I lived in China for 5 years',
        personality: 'Thoughtful, ambitious, dependable',
        favoriteMemory: 'Homecoming',
        littleQualities: ''
    },
    'Claudelle Cortez': {
        image: 'brothers/Claudelle_Justene_Cortez.jpg',
        fullName: 'Claudelle Cortez',
        pledgeClass: 'Sigma',
        graduationDate: 'May 2027',
        major: 'Economics',
        bio: 'Hey, I\'m Claudelle! I want to work with finance or data analytics in the entertainment industry, specifically music—my dream is to work at Spotify. Currently serving as Social Media Chair in DSP, I\'m also the Social Activities Chair for Women in Business. I work at Shake Shack and I used to coach tennis camp in high school. When I\'m not working or studying, I\'m journaling, playing tennis, reading, writing short stories, thrifting, or listening to music!',
        dspPositions: 'Social Media Chair (Spring 2026)',
        committees: 'Philanthropy (Spring 2026)',
        careerInterests: 'Finance or Data Analytics in Entertainment/Music Industry (dream: Spotify)',
        pastRoles: 'Social Activities Chair at Women In Business (May 2025 - Present), Food Service Worker at Shake Shack (Jun 2022 - Present), Tennis Camp Coach at Carle Place Middle Senior High School (Jun 2023 - Jul 2023)',
        linkedin: 'https://www.linkedin.com/in/claudelle-cortez-a83199355',
        email: 'claudellejuste.cortez@stonybrook.edu',
        hobbies: 'Journaling, playing tennis, reading, writing short stories, thrifting, listening to music',
        funFact: 'I played the violin for 10 years!',
        personality: 'Curious, Empathetic, and Compassionate',
        favoriteMemory: 'Staying up late to bake for our fundraiser or homecoming!',
        littleQualities: ''
    },
    'Natsumi Ekanayaka': {
        image: 'brothers/Natsumi Ekanayaka.jpeg',
        fullName: 'Natsumi Ekanayaka',
        pledgeClass: 'Sigma',
        graduationDate: 'May 2028',
        major: 'Business Mgmt (Marketing)',
        bio: 'Hey, I\'m Natsumi! I\'m into marketing and entrepreneurship. I\'ve worked as a Management Assistant at TOCO International and volunteered with NPO Child Doctor Japan. When I\'m not working or studying, I\'m reading, watching movies, playing piano or guitar, or shopping at malls.',
        dspPositions: 'n/a',
        committees: 'n/a',
        careerInterests: 'Marketing/Entrepreneurship',
        pastRoles: 'Management Assistant at Toco International (Jun 2024 - Aug 2024), Active Volunteer at NPO Child Doctor Japan (Aug 2023 - Aug 2024)',
        linkedin: 'https://www.linkedin.com/in/Natsumi-E',
        email: 'natsumi.ekanayaka@stonybrook.edu',
        hobbies: 'Reading, watching movies, playing piano + guitar, shopping at malls',
        funFact: 'I love the color pink',
        personality: 'Thoughtful, adaptable, warm',
        favoriteMemory: 'Pledge process + initiation!',
        littleQualities: ''
    },
    'Joshua Jacob': {
        image: 'brothers/Joshua Jacob.jpeg',
        fullName: 'Joshua Jacob',
        pledgeClass: 'Sigma',
        graduationDate: 'May 2027',
        major: 'Computer Science & Economics',
        bio: 'Hey, I\'m Joshua! I\'m into technology and data. I\'ve served as Public Relations Manager at Web Development Club and I was a Software Engineering Mentee at Google. I\'ve also worked as a Data Analyst Intern at Veolia North America and as a Research Team Leader at Blockchain Business Lab.',
        dspPositions: 'n/a',
        committees: 'n/a',
        careerInterests: '',
        pastRoles: 'Public Relations Manager at Web Development Club (May 2025 - Present), Software Engineering Mentee at Google (Jun 2025 - Sep 2025), Data Analyst Intern at Veolia North America (May 2025 - Aug 2025), Undergraduate Research Team Leader at Blockchain Business Lab (Jan 2025 - May 2025)',
        linkedin: 'https://www.linkedin.com/in/joshuasunnyjacob/',
        email: 'joshua.s.jacob@stonybrook.edu',
        hobbies: '',
        funFact: '',
        personality: '',
        favoriteMemory: '',
        littleQualities: ''
    },
    'James Kyung': {
        image: 'brothers/James Kyung.jpeg',
        fullName: 'James Kyung',
        pledgeClass: 'Sigma',
        graduationDate: 'May 2027',
        major: 'Business Mgmt',
        bio: 'Hey, I\'m James! I currently serve as Webmaster in DSP. I\'m a Tax Intern at Forvis Mazars US (incoming Spring 2027) and at Strategic Financial & Tax Planning Services (incoming Spring 2026). I\'m also a Senior Analyst at Fourier Fund and I\'ve done an Audit Internship at Skinnon & Faber.',
        dspPositions: 'Webmaster (Spring 2026)',
        committees: '',
        careerInterests: '',
        pastRoles: 'Tax Intern at Forvis Mazars US (Incoming Spring 2027), Tax Intern at Strategic Financial & Tax Planning Services (Incoming Spring 2026), Senior Analyst at Fourier Fund (Oct 2024 - Present), Audit Intern at Skinnon & Faber (Feb 2025 - Aug 2025), Campus Tour Guide at SBU (Sep 2023 - Dec 2024)',
        linkedin: 'https://www.linkedin.com/in/jameskyung/',
        email: 'james.kyung@stonybrook.edu',
        hobbies: '',
        funFact: '',
        personality: '',
        favoriteMemory: '',
        littleQualities: ''
    },
    'Ashley Lee': {
        image: 'brothers/Ashley Lee.jpeg',
        fullName: 'Ashley Lee',
        pledgeClass: 'Sigma',
        graduationDate: 'May 2028',
        major: 'Business Mgmt',
        bio: 'Hey, I\'m Ashley! I\'m into accounting/finance and currently serve as Social Chair in DSP. I\'m also Merch Chair at Women In Business and a Welcoming Team Member at Korean Christian Fellowship. I\'ve worked as a Senior Customer Service Representative at Enterprise Mobility and served as RHA Gray Hall Senator.',
        dspPositions: 'Social Chair (Spring 2026)',
        committees: 'PDC, Philanthropy (Spring 2026)',
        careerInterests: 'Accounting/finance',
        pastRoles: 'Social Chair at Delta Sigma Pi (Dec 2025 - Present), Merch Chair at Women In Business (Nov 2025 - Present), Senior Customer Service Representative at Enterprise Mobility (May 2025 - Oct 2025), RHA Gray Hall Senator at SBU (Jan 2025 - May 2025)',
        linkedin: 'https://www.linkedin.com/in/ashleyjalee',
        email: 'ashley.lee.1@stonybrook.edu',
        hobbies: 'Gym, handball, going to the city, baking',
        funFact: 'I\'ve fractured my finger twice, both from football',
        personality: 'Spontaneous, active, foodie',
        favoriteMemory: 'Pledging, hoco, and semis',
        littleQualities: ''
    },
    'Aldo Ramirez': {
        image: 'brothers/Aldo_Ramirez.jpg',
        fullName: 'Aldo Ramirez',
        pledgeClass: 'Sigma',
        graduationDate: 'May 2027',
        major: 'Business Mgmt (Operations), Minor in Accounting',
        bio: 'Hey, I\'m Aldo! I\'m into accounting, getting my CPA, and HR. Currently serving as Philanthropy Chair in DSP, I\'m involved in the VITA Program. I work as a Team Leader at Chick-fil-A. When I\'m not working or studying, I\'m running, playing soccer or volleyball, or listening to music.',
        dspPositions: 'Philanthropy Chair (Spring 2026)',
        committees: 'Philanthropy',
        careerInterests: 'Accounting, CPA, HR',
        pastRoles: 'Philanthropy Chairperson at Delta Sigma Pi (Dec 2025 - Present), Team Leader at Chick-fil-A Restaurants (Jun 2024 - Present), VITA Program',
        linkedin: 'https://www.linkedin.com/in/aldramirez',
        email: 'aldo.ramirez@stonybrook.edu',
        hobbies: 'Running, Soccer, Volleyball, Sports, Music',
        funFact: 'I\'ve run 2 marathons so far. I love listening to new music',
        personality: '',
        favoriteMemory: 'Hoco',
        littleQualities: ''
    },
    'Jahzeel Requena': {
        image: 'brothers/Jahzeel Requena.jpeg',
        fullName: 'Jahzeel Requena',
        pledgeClass: 'Sigma',
        graduationDate: 'May 2028',
        major: 'Technological Systems Management',
        bio: 'Hey, I\'m Jahzeel! I\'m into project management. I work as a Student Technician for DoIT and I\'ve been a Residential Ambassador for the Pre-College Summer Program. I also have experience as an AV Technician. When I\'m not working or studying, I\'m playing video games, reading, writing, listening to music, or playing basketball.',
        dspPositions: 'n/a',
        committees: 'Community Service, Alumni Relations (Spring 2026)',
        careerInterests: 'Project Management',
        pastRoles: 'Student Technician at SBU (Mar 2025 - Present), Residential Ambassador at SBU (Jun 2025 - Jul 2025), AV Technician at Bronx Seventh Day Adventist Church (Feb 2022 - Jul 2024)',
        linkedin: 'https://www.linkedin.com/in/jahzeel-requena',
        email: 'jahzeel.requena@stonybrook.edu',
        hobbies: 'Videogames, reading, writing, listening to music, and basketball',
        funFact: 'I have a brown belt in karate',
        personality: 'Swag, calm, agreeable',
        favoriteMemory: 'Homecoming',
        littleQualities: ''
    },
    'Reon Sarkar': {
        image: 'brothers/Reon Sarkar.jpeg',
        fullName: 'Reon Sarkar',
        pledgeClass: 'Sigma',
        graduationDate: 'May 2028',
        major: 'Technological Systems Management (ISE)',
        bio: 'Hey, I\'m Reon! I\'m into IT, tech, and consulting. I\'ve worked as a Network Operations Intern at Spellman High Voltage and I currently work as a Sales Advisor at Best Buy. When I\'m not working or studying, I\'m playing video games, watching TV shows, cooking, or working out.',
        dspPositions: 'n/a',
        committees: 'Professional Development, Community Service, Philanthropy (Spring 2026)',
        careerInterests: 'IT, Tech, Consulting',
        pastRoles: 'Sales Advisor at Best Buy (Sep 2025 - Present), Network Operations Intern at Spellman High Voltage (Jun 2025 - Aug 2025)',
        linkedin: 'https://www.linkedin.com/in/reon-sarkar',
        email: 'reon.sarkar@stonybrook.edu',
        hobbies: 'Video Games, tv shows, cooking, working out',
        funFact: 'I was bit by a cobra',
        personality: '',
        favoriteMemory: 'Homecoming',
        littleQualities: ''
    },
    'William Sim': {
        image: 'brothers/William Sim.jpeg',
        fullName: 'William Sim',
        pledgeClass: 'Sigma',
        graduationDate: 'May 2027',
        major: 'Business Mgmt & Marketing',
        bio: 'Hey, I\'m William! I currently serve as Marketing Chair in DSP. I have an incoming Design Management Intern position at Warner Bros. Discovery and I work as a Graphic Designer for SBU Athletics and Esports. I also do graphic design work for Rosewood Creative, FaZe Clan, and NRG Esports.',
        dspPositions: 'Marketing Chair (Spring 2026)',
        committees: '',
        careerInterests: '',
        pastRoles: 'Incoming Design Management Intern at Warner Bros. Discovery (Dec 2025 - Present), Graphic Designer - Esports at SBU (Sep 2025 - Present), Creative Content – SBU Athletics Student Assistant (Sep 2025 - Present), Graphic Designer at Rosewood Creative (Aug 2024 - Present), Graphic Designer at FaZe Clan (May 2024 - Present), Graphic Designer at NRG Esports (Nov 2022 - Aug 2024)',
        linkedin: 'https://www.linkedin.com/in/williamsimjr/',
        email: 'william.sim@stonybrook.edu',
        hobbies: '',
        funFact: '',
        personality: '',
        favoriteMemory: '',
        littleQualities: ''
    },
    'Jaden Yang': {
        image: 'brothers/Jaden Yang.JPG',
        fullName: 'Jaden Yang',
        pledgeClass: 'Sigma',
        graduationDate: 'May 2028',
        major: 'Applied Math/Statistics',
        bio: 'Hey, I\'m Jaden! I\'m interested in actuary, accounting, data, finance, operations, and consulting. I work as a DoIT Client Support Technician/Assistant Project Manager and I\'m Korean Student Association Historian. I also tutor math freelance and I\'ve worked as an Assistant Manager at Bounce! Trampoline Park. When I\'m not working or studying, I\'m playing basketball, weightlifting, shopping, taking photos, listening to music, or playing video games.',
        dspPositions: 'n/a',
        committees: 'n/a',
        careerInterests: 'Actuary, Accounting, Data, Finance, Operations, Consulting',
        pastRoles: 'Client Support Assistant Project Manager at SBU (Sep 2025 - Present), Client Support Technician at SBU (May 2025 - Present), Mathematics Tutor (Freelance) (Aug 2022 - Present), Assistant Manager at Bounce! Trampoline Park (Dec 2023 - Aug 2024), Korean Student Association Historian',
        linkedin: 'https://www.linkedin.com/in/jadenyngg/',
        email: 'jaden.yang@stonybrook.edu',
        hobbies: 'Basketball, weightlifting, fashion, shopping, photography, music, cats, cars, good food, video games',
        funFact: 'I used to produce music',
        personality: 'Compassionate, ambitious, chill',
        favoriteMemory: 'Homecoming with the brothers',
        littleQualities: ''
    }
};

