// Brothers profile data
const brothersData = {
    'Aidan Chan': {
        image: 'brothers/Aidan Chan.jpg',
        fullName: 'Aidan Chan',
        pledgeClass: 'Rho',
        graduationDate: 'May 2027',
        major: 'Business Major / Specialization in Finance',
        bio: 'What\'s up! I\'m Aidan, a Business major with a specialization in Finance, graduating in May 2027. I\'m passionate about financial analysis and entrepreneurship, especially starting and owning my own barbershop. I founded Herb Fades, a successful barbering business serving 150+ clients on campus, and I love combining my business skills with my passion for helping people look and feel their best. When I\'m not cutting hair or studying, you\'ll find me playing basketball, eating good food, and gaming with friends.',
        dspPositions: '',
        committees: 'Philanthropy (Fall 2025)',
        careerInterests: 'Financial Analyst, Starting and owning my own barbershop',
        pastRoles: 'Founder at Herb Fades (Dec 2022 - Present), Food Server at Luigi\'s Restaurant & Bar (Jul 2022 - Aug 2023), Customer Service Representative at eFresh (Jul 2020 - Oct 2021)',
        linkedin: 'https://www.linkedin.com/in/aidanchan27',
        email: 'aidan.chan@stonybrook.edu',
        hobbies: 'Basketball, eating, playing games',
        funFact: 'I am recently bilingual',
        personality: 'Smile, outgoing, chill',
        favoriteMemory: 'Baking and playing games with my fellow brothers',
        littleQualities: ''
    },
    'Ana Jiang': {
        image: 'brothers/Ana Jiang.jpeg',
        fullName: 'Ana Jiang',
        pledgeClass: 'Rho',
        graduationDate: 'May 2027',
        major: 'Business Management with Specialization in Operations, Minor in Accounting',
        bio: 'Hello! I\'m Ana, a Business Management major with a specialization in Operations and a minor in Accounting, graduating in May 2027. I\'m passionate about human resources and audit, and I love bringing people together through meaningful work. Currently serving as Philanthropy Chair at DSP and Human Resources Manager at Fourier Fund, I\'ve gained extensive experience in talent management, operations, and event coordination. When I\'m not working, you\'ll find me hiking, traveling, taking pictures, and enjoying matcha!',
        dspPositions: 'Philanthropy Chair (Fall 2025)',
        committees: 'Standards, Philanthropy (Fall 2025)',
        careerInterests: 'Human Resources, Audit',
        pastRoles: 'Student Engagement Specialist at Ion Philanthropy (Oct 2025 - Present), Undergraduate Teaching Assistant at Stony Brook University (Aug 2025 - Present), Philanthropy Chairperson at Delta Sigma Pi (May 2025 - Present), Human Resources Manager at Fourier Fund (Mar 2025 - Present), Operations & Talent Management Intern at SBU Career Center (Aug 2024 - May 2025), Sales Associate at Rumi Life (Oct 2023 - May 2025)',
        linkedin: 'https://www.linkedin.com/in/ana-jiang',
        email: 'ana.jiang@stonybrook.edu',
        hobbies: 'Hiking, traveling, taking pictures, and LOVE MATCHA',
        funFact: '',
        personality: '',
        favoriteMemory: '',
        littleQualities: ''
    },
    'Camila Sanchez': {
        image: 'brothers/Camila Sanchez.JPG',
        fullName: 'Camila Sanchez',
        pledgeClass: 'Rho',
        graduationDate: 'May 2028',
        major: 'Business Major specializing in Marketing',
        bio: 'Hi there! I\'m Camila, a Business major specializing in Marketing, graduating in May 2028. I\'m passionate about marketing and public relations, and I love bringing creative ideas to life through social media and brand storytelling. Currently serving as Social Media Chair and Recruitment Chair at DSP, I\'ve designed 30+ branded posts and grown our social media engagement significantly. When I\'m not creating content, you\'ll find me listening to music (huge Lana del Rey and The Neighbourhood fan!), reading, dancing, or working on coloring books. Just don\'t bring any bugs near me!',
        dspPositions: 'Social Media Chair (Fall 2025), Recruitment Chair (Spring 2026)',
        committees: 'CS/ Philanthropy (Fall 2025), AR/ Philanthropy (Spring 2026)',
        careerInterests: 'Marketing, Public Relations',
        pastRoles: 'Social Media Chair at Delta Sigma Pi (May 2025 - Present), Residential Ambassador at Stony Brook University (Jun 2025 - Jul 2025), Project and Event Coordinator Intern at SBU, Childcare Worker at Marks JCH of Bensonhurst (Sep 2022 - Jun 2024)',
        linkedin: 'https://www.linkedin.com/in/camila6',
        email: 'camila.sanchez@stonybrook.edu',
        hobbies: 'Music, Coloring books, Reading, Dance',
        funFact: 'I love dying my hair, I\'m a huge fan of Lana del Ray and The Neighbourhood, and I am scared of bugs',
        personality: 'Bright, SMILE, Hardworking',
        favoriteMemory: 'Going out to any social event with my friends in DSP',
        littleQualities: ''
    },
    'Chanul Dandeniya': {
        image: 'brothers/Chanul Dandeniya.jpeg',
        fullName: 'Chanul Dandeniya',
        pledgeClass: 'Rho',
        graduationDate: 'May 2027',
        major: 'Computer Science, Applied Mathematics & Statistics',
        bio: 'What\'s up! I\'m Chanul, a CS and AMS major graduating in May 2027, passionate about software engineering, technical product management, and startup culture. With extensive experience at Amazon, AI startups, and leading brand strategy at Outer Labs Studio, I combine technical expertise with strategic thinking. Outside of tech, I enjoy hitting the gym, building side projects, playing basketball, and spontaneous hangouts with friends.',
        dspPositions: '',
        committees: '',
        careerInterests: 'Software Engineering, Technical Product Management, Startup Culture',
        pastRoles: 'Junior Developer at Amazon (Oct 2021 - Oct 2024), Machine Learning Intern at SAI AI, Lead Solutions Architect at OuterLabs Studio (Aug 2022 - Jun 2025)',
        linkedin: 'https://www.linkedin.com/in/cdandeniya/',
        email: 'chanul.dandeniya@stonybrook.edu',
        hobbies: 'Gymming, building apps, basketball, real estate, investing, spontaneity',
        funFact: '',
        personality: '',
        favoriteMemory: 'Skydiving with my big and chilling with the brothers',
        littleQualities: ''
    }
};

